using System;
using JetBrains.Annotations;

namespace Naninovel
{
    /// <summary>
    /// Optional preferences of a <see cref="Choice"/>.
    /// </summary>
    [Serializable]
    public struct ChoiceOptions
    {
        /// <summary>
        /// Unique identifier of the choice.
        /// Auto-generated by default.
        /// </summary>
        [CanBeNull] public string Id;
        /// <summary>
        /// Text describing consequences of this choice.
        /// Not displayed by default.
        /// </summary>
        public LocalizableText Summary;
        /// <summary>
        /// Whether to lock/disable the choice.
        /// </summary>
        public bool Lock;
        /// <summary>
        /// Local resource path of the button prefab representing the choice.
        /// Uses choice prefab assigned on the handler by default.
        /// </summary>
        [CanBeNull] public string ButtonPath;
        /// <summary>
        /// Local position of the choice button inside the choice handler.
        /// Auto-position by default.
        /// </summary>
        [CanBeNull] public NullableVector2 ButtonPosition;
    }
}
