using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class abnormalcondition : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5571372956317667142UL,10679110987833586591UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String conditionId
		{
			get => _conditionId[Index];
			set => _conditionId[Index] = value;
		}
		public System.String memo
		{
			get => _memo[Index];
			set => _memo[Index] = value;
		}
		public System.String conditionCategory
		{
			get => _conditionCategory[Index];
			set => _conditionCategory[Index] = value;
		}
		public System.Int32 probability
		{
			get => _probability[Index];
			set => _probability.SetValue(this, value);
		}
		public System.String activationCondition
		{
			get => _activationCondition[Index];
			set => _activationCondition[Index] = value;
		}
		public System.String gender
		{
			get => _gender[Index];
			set => _gender[Index] = value;
		}
		public System.String tag1
		{
			get => _tag1[Index];
			set => _tag1[Index] = value;
		}
		public System.String tag2
		{
			get => _tag2[Index];
			set => _tag2[Index] = value;
		}
		public System.String typeId
		{
			get => _typeId[Index];
			set => _typeId[Index] = value;
		}
		public System.String effectTarget
		{
			get => _effectTarget[Index];
			set => _effectTarget[Index] = value;
		}
		public System.String consumeTiming
		{
			get => _consumeTiming[Index];
			set => _consumeTiming[Index] = value;
		}
		public System.String turnCount
		{
			get => _turnCount[Index];
			set => _turnCount[Index] = value;
		}
		public System.String effectType1
		{
			get => _effectType1[Index];
			set => _effectType1[Index] = value;
		}
		public System.Int32 effectValue1
		{
			get => _effectValue1[Index];
			set => _effectValue1.SetValue(this, value);
		}
		public System.String effectType2
		{
			get => _effectType2[Index];
			set => _effectType2[Index] = value;
		}
		public System.Int32 effectValue2
		{
			get => _effectValue2[Index];
			set => _effectValue2.SetValue(this, value);
		}
		public System.String effectType3
		{
			get => _effectType3[Index];
			set => _effectType3[Index] = value;
		}
		public System.Int32 effectValue3
		{
			get => _effectValue3[Index];
			set => _effectValue3.SetValue(this, value);
		}
		public System.Int32 poisonHpDamageRate
		{
			get => _poisonHpDamageRate[Index];
			set => _poisonHpDamageRate.SetValue(this, value);
		}
		public System.Int32 paralysisActionRate
		{
			get => _paralysisActionRate[Index];
			set => _paralysisActionRate.SetValue(this, value);
		}
		public System.Int32 confusionActionRate
		{
			get => _confusionActionRate[Index];
			set => _confusionActionRate.SetValue(this, value);
		}
		public System.Int32 burnHpDamageRate
		{
			get => _burnHpDamageRate[Index];
			set => _burnHpDamageRate.SetValue(this, value);
		}
		public System.Int32 burnAtkReduceRate
		{
			get => _burnAtkReduceRate[Index];
			set => _burnAtkReduceRate.SetValue(this, value);
		}
		public System.Int32 doomTurnCount
		{
			get => _doomTurnCount[Index];
			set => _doomTurnCount.SetValue(this, value);
		}
		public System.String attachedBuffId1
		{
			get => _attachedBuffId1[Index];
			set => _attachedBuffId1[Index] = value;
		}
		public System.String attachedBuffId2
		{
			get => _attachedBuffId2[Index];
			set => _attachedBuffId2[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5171154071789511488UL, 9668251446286079931UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_conditionId;
		public static BansheeGz.BGDatabase.BGFieldString _conditionId => _ufle12jhs77_conditionId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4635848067602334562UL, 15340752757249110417UL), () => _ufle12jhs77_conditionId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_memo;
		public static BansheeGz.BGDatabase.BGFieldString _memo => _ufle12jhs77_memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5265499742171453130UL, 7361177341536616077UL), () => _ufle12jhs77_memo = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_conditionCategory;
		public static BansheeGz.BGDatabase.BGFieldString _conditionCategory => _ufle12jhs77_conditionCategory ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5083019440419739607UL, 14344033681965895356UL), () => _ufle12jhs77_conditionCategory = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_probability;
		public static BansheeGz.BGDatabase.BGFieldInt _probability => _ufle12jhs77_probability ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5392016732617833329UL, 705193741023523980UL), () => _ufle12jhs77_probability = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_activationCondition;
		public static BansheeGz.BGDatabase.BGFieldString _activationCondition => _ufle12jhs77_activationCondition ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5101670378730896394UL, 3711990384173717692UL), () => _ufle12jhs77_activationCondition = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_gender;
		public static BansheeGz.BGDatabase.BGFieldString _gender => _ufle12jhs77_gender ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5413739509775861411UL, 115234351969011368UL), () => _ufle12jhs77_gender = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_tag1;
		public static BansheeGz.BGDatabase.BGFieldString _tag1 => _ufle12jhs77_tag1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4785134287183922914UL, 7054056355321891475UL), () => _ufle12jhs77_tag1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_tag2;
		public static BansheeGz.BGDatabase.BGFieldString _tag2 => _ufle12jhs77_tag2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4755590936128731124UL, 4131268378458540949UL), () => _ufle12jhs77_tag2 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_typeId;
		public static BansheeGz.BGDatabase.BGFieldString _typeId => _ufle12jhs77_typeId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4994271164916252374UL, 545136052724525219UL), () => _ufle12jhs77_typeId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_effectTarget;
		public static BansheeGz.BGDatabase.BGFieldString _effectTarget => _ufle12jhs77_effectTarget ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5398523903401147669UL, 14869467623333315214UL), () => _ufle12jhs77_effectTarget = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_consumeTiming;
		public static BansheeGz.BGDatabase.BGFieldString _consumeTiming => _ufle12jhs77_consumeTiming ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4928740288700789031UL, 16336501877368294066UL), () => _ufle12jhs77_consumeTiming = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_turnCount;
		public static BansheeGz.BGDatabase.BGFieldString _turnCount => _ufle12jhs77_turnCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5459838525852887778UL, 11256244214158411175UL), () => _ufle12jhs77_turnCount = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_effectType1;
		public static BansheeGz.BGDatabase.BGFieldString _effectType1 => _ufle12jhs77_effectType1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5500029551414714376UL, 11294346333581698694UL), () => _ufle12jhs77_effectType1 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_effectValue1;
		public static BansheeGz.BGDatabase.BGFieldInt _effectValue1 => _ufle12jhs77_effectValue1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5660689749432343524UL, 13377645409357028001UL), () => _ufle12jhs77_effectValue1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_effectType2;
		public static BansheeGz.BGDatabase.BGFieldString _effectType2 => _ufle12jhs77_effectType2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5450539404667789681UL, 1511227276933013132UL), () => _ufle12jhs77_effectType2 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_effectValue2;
		public static BansheeGz.BGDatabase.BGFieldInt _effectValue2 => _ufle12jhs77_effectValue2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4656820453813501542UL, 11354477618132455100UL), () => _ufle12jhs77_effectValue2 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_effectType3;
		public static BansheeGz.BGDatabase.BGFieldString _effectType3 => _ufle12jhs77_effectType3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4903361368271860350UL, 3287433151776113549UL), () => _ufle12jhs77_effectType3 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_effectValue3;
		public static BansheeGz.BGDatabase.BGFieldInt _effectValue3 => _ufle12jhs77_effectValue3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5608456131238998507UL, 13022089042193087389UL), () => _ufle12jhs77_effectValue3 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_poisonHpDamageRate;
		public static BansheeGz.BGDatabase.BGFieldInt _poisonHpDamageRate => _ufle12jhs77_poisonHpDamageRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4771992185391749000UL, 10970266417557742468UL), () => _ufle12jhs77_poisonHpDamageRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_paralysisActionRate;
		public static BansheeGz.BGDatabase.BGFieldInt _paralysisActionRate => _ufle12jhs77_paralysisActionRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5609875572534665664UL, 15664812625723418531UL), () => _ufle12jhs77_paralysisActionRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_confusionActionRate;
		public static BansheeGz.BGDatabase.BGFieldInt _confusionActionRate => _ufle12jhs77_confusionActionRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5736167376288022483UL, 6796984943856570776UL), () => _ufle12jhs77_confusionActionRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_burnHpDamageRate;
		public static BansheeGz.BGDatabase.BGFieldInt _burnHpDamageRate => _ufle12jhs77_burnHpDamageRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5385220647853674419UL, 8711410342085636531UL), () => _ufle12jhs77_burnHpDamageRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_burnAtkReduceRate;
		public static BansheeGz.BGDatabase.BGFieldInt _burnAtkReduceRate => _ufle12jhs77_burnAtkReduceRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4857696108406581367UL, 14963172996642984362UL), () => _ufle12jhs77_burnAtkReduceRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_doomTurnCount;
		public static BansheeGz.BGDatabase.BGFieldInt _doomTurnCount => _ufle12jhs77_doomTurnCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5175033093695105633UL, 13163328294357415613UL), () => _ufle12jhs77_doomTurnCount = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_attachedBuffId1;
		public static BansheeGz.BGDatabase.BGFieldString _attachedBuffId1 => _ufle12jhs77_attachedBuffId1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5636943192004502552UL, 119439268795190715UL), () => _ufle12jhs77_attachedBuffId1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_attachedBuffId2;
		public static BansheeGz.BGDatabase.BGFieldString _attachedBuffId2 => _ufle12jhs77_attachedBuffId2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4918945830581261863UL, 7821254156194916750UL), () => _ufle12jhs77_attachedBuffId2 = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_abnormalconditionKey;
		public static BansheeGz.BGDatabase.BGKey _abnormalconditionKey => _edeht3sdad33_abnormalconditionKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(4753788300357244029UL, 1291888561239100032UL), () => _edeht3sdad33_abnormalconditionKey = null);
		private abnormalcondition() : base(MetaDefault) {}
		private abnormalcondition(BGId id) : base(MetaDefault, id) {}
		private abnormalcondition(BGMetaEntity meta) : base(meta) {}
		private abnormalcondition(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static abnormalcondition FindEntity(Predicate<abnormalcondition> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<abnormalcondition> FindEntities(Predicate<abnormalcondition> filter, List<abnormalcondition> result=null, Comparison<abnormalcondition> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<abnormalcondition> action, Predicate<abnormalcondition> filter=null, Comparison<abnormalcondition> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static abnormalcondition GetEntity(BGId entityId) => (abnormalcondition) MetaDefault.GetEntity(entityId);
		public static abnormalcondition GetEntity(int index) => (abnormalcondition) MetaDefault[index];
		public static abnormalcondition GetEntity(string entityName) => (abnormalcondition) MetaDefault.GetEntity(entityName);
		public static abnormalcondition NewEntity() => (abnormalcondition) MetaDefault.NewEntity();
		public static abnormalcondition NewEntity(BGId entityId) => (abnormalcondition) MetaDefault.NewEntity(entityId);
		public static abnormalcondition NewEntity(Action<abnormalcondition> callback) => (abnormalcondition) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((abnormalcondition)entity)));
		public static abnormalcondition GetEntityByKeyabnormalconditionKey(System.String conditionId) => (abnormalcondition) _abnormalconditionKey.GetEntityByKey<System.String>(conditionId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5571372956317667142UL,10679110987833586591UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5171154071789511488UL, 9668251446286079931UL));
			_ufle12jhs77_conditionId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4635848067602334562UL, 15340752757249110417UL));
			_ufle12jhs77_memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5265499742171453130UL, 7361177341536616077UL));
			_ufle12jhs77_conditionCategory = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5083019440419739607UL, 14344033681965895356UL));
			_ufle12jhs77_probability = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5392016732617833329UL, 705193741023523980UL));
			_ufle12jhs77_activationCondition = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5101670378730896394UL, 3711990384173717692UL));
			_ufle12jhs77_gender = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5413739509775861411UL, 115234351969011368UL));
			_ufle12jhs77_tag1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4785134287183922914UL, 7054056355321891475UL));
			_ufle12jhs77_tag2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4755590936128731124UL, 4131268378458540949UL));
			_ufle12jhs77_typeId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4994271164916252374UL, 545136052724525219UL));
			_ufle12jhs77_effectTarget = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5398523903401147669UL, 14869467623333315214UL));
			_ufle12jhs77_consumeTiming = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4928740288700789031UL, 16336501877368294066UL));
			_ufle12jhs77_turnCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5459838525852887778UL, 11256244214158411175UL));
			_ufle12jhs77_effectType1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5500029551414714376UL, 11294346333581698694UL));
			_ufle12jhs77_effectValue1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5660689749432343524UL, 13377645409357028001UL));
			_ufle12jhs77_effectType2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5450539404667789681UL, 1511227276933013132UL));
			_ufle12jhs77_effectValue2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4656820453813501542UL, 11354477618132455100UL));
			_ufle12jhs77_effectType3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4903361368271860350UL, 3287433151776113549UL));
			_ufle12jhs77_effectValue3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5608456131238998507UL, 13022089042193087389UL));
			_ufle12jhs77_poisonHpDamageRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4771992185391749000UL, 10970266417557742468UL));
			_ufle12jhs77_paralysisActionRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5609875572534665664UL, 15664812625723418531UL));
			_ufle12jhs77_confusionActionRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5736167376288022483UL, 6796984943856570776UL));
			_ufle12jhs77_burnHpDamageRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5385220647853674419UL, 8711410342085636531UL));
			_ufle12jhs77_burnAtkReduceRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4857696108406581367UL, 14963172996642984362UL));
			_ufle12jhs77_doomTurnCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5175033093695105633UL, 13163328294357415613UL));
			_ufle12jhs77_attachedBuffId1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5636943192004502552UL, 119439268795190715UL));
			_ufle12jhs77_attachedBuffId2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4918945830581261863UL, 7821254156194916750UL));
			_edeht3sdad33_abnormalconditionKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(4753788300357244029UL, 1291888561239100032UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_conditionId = null;
			_ufle12jhs77_memo = null;
			_ufle12jhs77_conditionCategory = null;
			_ufle12jhs77_probability = null;
			_ufle12jhs77_activationCondition = null;
			_ufle12jhs77_gender = null;
			_ufle12jhs77_tag1 = null;
			_ufle12jhs77_tag2 = null;
			_ufle12jhs77_typeId = null;
			_ufle12jhs77_effectTarget = null;
			_ufle12jhs77_consumeTiming = null;
			_ufle12jhs77_turnCount = null;
			_ufle12jhs77_effectType1 = null;
			_ufle12jhs77_effectValue1 = null;
			_ufle12jhs77_effectType2 = null;
			_ufle12jhs77_effectValue2 = null;
			_ufle12jhs77_effectType3 = null;
			_ufle12jhs77_effectValue3 = null;
			_ufle12jhs77_poisonHpDamageRate = null;
			_ufle12jhs77_paralysisActionRate = null;
			_ufle12jhs77_confusionActionRate = null;
			_ufle12jhs77_burnHpDamageRate = null;
			_ufle12jhs77_burnAtkReduceRate = null;
			_ufle12jhs77_doomTurnCount = null;
			_ufle12jhs77_attachedBuffId1 = null;
			_ufle12jhs77_attachedBuffId2 = null;
			_edeht3sdad33_abnormalconditionKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new abnormalcondition(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new abnormalcondition(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "abnormalcondition";
			public const string name = "name";
			public const string conditionId = "conditionId";
			public const string memo = "memo";
			public const string conditionCategory = "conditionCategory";
			public const string probability = "probability";
			public const string activationCondition = "activationCondition";
			public const string gender = "gender";
			public const string tag1 = "tag1";
			public const string tag2 = "tag2";
			public const string typeId = "typeId";
			public const string effectTarget = "effectTarget";
			public const string consumeTiming = "consumeTiming";
			public const string turnCount = "turnCount";
			public const string effectType1 = "effectType1";
			public const string effectValue1 = "effectValue1";
			public const string effectType2 = "effectType2";
			public const string effectValue2 = "effectValue2";
			public const string effectType3 = "effectType3";
			public const string effectValue3 = "effectValue3";
			public const string poisonHpDamageRate = "poisonHpDamageRate";
			public const string paralysisActionRate = "paralysisActionRate";
			public const string confusionActionRate = "confusionActionRate";
			public const string burnHpDamageRate = "burnHpDamageRate";
			public const string burnAtkReduceRate = "burnAtkReduceRate";
			public const string doomTurnCount = "doomTurnCount";
			public const string attachedBuffId1 = "attachedBuffId1";
			public const string attachedBuffId2 = "attachedBuffId2";
			public const string abnormalconditionKey = "abnormalconditionKey";
		}
	}
}
#pragma warning restore 414
