using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class buffdebuff : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4699993827280895298UL,17438361447795262139UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String buffId
		{
			get => _buffId[Index];
			set => _buffId[Index] = value;
		}
		public System.String memo
		{
			get => _memo[Index];
			set => _memo[Index] = value;
		}
		public System.String activationCondition
		{
			get => _activationCondition[Index];
			set => _activationCondition[Index] = value;
		}
		public System.String tag1
		{
			get => _tag1[Index];
			set => _tag1[Index] = value;
		}
		public System.String tag2
		{
			get => _tag2[Index];
			set => _tag2[Index] = value;
		}
		public System.String gender
		{
			get => _gender[Index];
			set => _gender[Index] = value;
		}
		public System.Int32 activationRate
		{
			get => _activationRate[Index];
			set => _activationRate.SetValue(this, value);
		}
		public System.Int32 turnCount
		{
			get => _turnCount[Index];
			set => _turnCount.SetValue(this, value);
		}
		public System.String effectTarget
		{
			get => _effectTarget[Index];
			set => _effectTarget[Index] = value;
		}
		public System.String consumeTiming
		{
			get => _consumeTiming[Index];
			set => _consumeTiming[Index] = value;
		}
		public System.String powerUpTiming
		{
			get => _powerUpTiming[Index];
			set => _powerUpTiming[Index] = value;
		}
		public System.Int32 maxStacks
		{
			get => _maxStacks[Index];
			set => _maxStacks.SetValue(this, value);
		}
		public System.String buffType1
		{
			get => _buffType1[Index];
			set => _buffType1[Index] = value;
		}
		public System.Int32 buffValue1
		{
			get => _buffValue1[Index];
			set => _buffValue1.SetValue(this, value);
		}
		public System.String specialEffectTag1
		{
			get => _specialEffectTag1[Index];
			set => _specialEffectTag1[Index] = value;
		}
		public System.String valueModifierType1
		{
			get => _valueModifierType1[Index];
			set => _valueModifierType1[Index] = value;
		}
		public List<type> typeId
		{
			get => BGCodeGenUtils.MultipleRelationGet<type>(_typeId, Index);
			set => BGCodeGenUtils.MultipleRelationSet<type>(_typeId, Index, value);
		}
		public System.Boolean unerasableFlag
		{
			get => _unerasableFlag[Index];
			set => _unerasableFlag.SetValue(this, value);
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4687238973632179271UL, 1864200036504196287UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_buffId;
		public static BansheeGz.BGDatabase.BGFieldString _buffId => _ufle12jhs77_buffId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5657514695913066624UL, 6993011482850646692UL), () => _ufle12jhs77_buffId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_memo;
		public static BansheeGz.BGDatabase.BGFieldString _memo => _ufle12jhs77_memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5514847217024097780UL, 5213281375434653581UL), () => _ufle12jhs77_memo = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_activationCondition;
		public static BansheeGz.BGDatabase.BGFieldString _activationCondition => _ufle12jhs77_activationCondition ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4811428152361450916UL, 3550964937271853238UL), () => _ufle12jhs77_activationCondition = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_tag1;
		public static BansheeGz.BGDatabase.BGFieldString _tag1 => _ufle12jhs77_tag1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5532208521926524070UL, 2804432832839120039UL), () => _ufle12jhs77_tag1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_tag2;
		public static BansheeGz.BGDatabase.BGFieldString _tag2 => _ufle12jhs77_tag2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5167644421136567475UL, 3637738721041258135UL), () => _ufle12jhs77_tag2 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_gender;
		public static BansheeGz.BGDatabase.BGFieldString _gender => _ufle12jhs77_gender ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5490807830882938108UL, 15542905561820646529UL), () => _ufle12jhs77_gender = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_activationRate;
		public static BansheeGz.BGDatabase.BGFieldInt _activationRate => _ufle12jhs77_activationRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4839298101478417852UL, 8425764103347763601UL), () => _ufle12jhs77_activationRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_turnCount;
		public static BansheeGz.BGDatabase.BGFieldInt _turnCount => _ufle12jhs77_turnCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5082909908324151192UL, 11865525294893584787UL), () => _ufle12jhs77_turnCount = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_effectTarget;
		public static BansheeGz.BGDatabase.BGFieldString _effectTarget => _ufle12jhs77_effectTarget ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5364245553622036372UL, 176893375286428336UL), () => _ufle12jhs77_effectTarget = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_consumeTiming;
		public static BansheeGz.BGDatabase.BGFieldString _consumeTiming => _ufle12jhs77_consumeTiming ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5108606903378487452UL, 8212737381671945656UL), () => _ufle12jhs77_consumeTiming = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_powerUpTiming;
		public static BansheeGz.BGDatabase.BGFieldString _powerUpTiming => _ufle12jhs77_powerUpTiming ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5417264663178438202UL, 14927538864030012055UL), () => _ufle12jhs77_powerUpTiming = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_maxStacks;
		public static BansheeGz.BGDatabase.BGFieldInt _maxStacks => _ufle12jhs77_maxStacks ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5070375692578368098UL, 9903950123912365490UL), () => _ufle12jhs77_maxStacks = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_buffType1;
		public static BansheeGz.BGDatabase.BGFieldString _buffType1 => _ufle12jhs77_buffType1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5436221321068810921UL, 9593245426072740246UL), () => _ufle12jhs77_buffType1 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_buffValue1;
		public static BansheeGz.BGDatabase.BGFieldInt _buffValue1 => _ufle12jhs77_buffValue1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5420376048428271068UL, 13682774272955766459UL), () => _ufle12jhs77_buffValue1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_specialEffectTag1;
		public static BansheeGz.BGDatabase.BGFieldString _specialEffectTag1 => _ufle12jhs77_specialEffectTag1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5740474805537465056UL, 11125338150783074699UL), () => _ufle12jhs77_specialEffectTag1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_valueModifierType1;
		public static BansheeGz.BGDatabase.BGFieldString _valueModifierType1 => _ufle12jhs77_valueModifierType1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4617256288311391142UL, 8507679789460896139UL), () => _ufle12jhs77_valueModifierType1 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationMultiple _ufle12jhs77_typeId;
		public static BansheeGz.BGDatabase.BGFieldRelationMultiple _typeId => _ufle12jhs77_typeId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(MetaDefault, new BGId(4920717210643321025UL, 3211686099010039174UL), () => _ufle12jhs77_typeId = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_unerasableFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _unerasableFlag => _ufle12jhs77_unerasableFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5758501882099323519UL, 14829223627322287016UL), () => _ufle12jhs77_unerasableFlag = null);
		public List<Iono.MasterData.skill> RelatedskillListUsingtargetBuffIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.skill>(Iono.MasterData.skill._targetBuffId, Id);
		public List<Iono.MasterData.skill> RelatedskillListUsinguserBuffIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.skill>(Iono.MasterData.skill._userBuffId, Id);
		public List<Iono.MasterData.inventory> RelatedinventoryListUsingbuffdebuffIDRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.inventory>(Iono.MasterData.inventory._buffdebuffID, Id);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_buffKey;
		public static BansheeGz.BGDatabase.BGKey _buffKey => _edeht3sdad33_buffKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5701269069400636383UL, 4078363698253069977UL), () => _edeht3sdad33_buffKey = null);
		private buffdebuff() : base(MetaDefault) {}
		private buffdebuff(BGId id) : base(MetaDefault, id) {}
		private buffdebuff(BGMetaEntity meta) : base(meta) {}
		private buffdebuff(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static buffdebuff FindEntity(Predicate<buffdebuff> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<buffdebuff> FindEntities(Predicate<buffdebuff> filter, List<buffdebuff> result=null, Comparison<buffdebuff> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<buffdebuff> action, Predicate<buffdebuff> filter=null, Comparison<buffdebuff> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static buffdebuff GetEntity(BGId entityId) => (buffdebuff) MetaDefault.GetEntity(entityId);
		public static buffdebuff GetEntity(int index) => (buffdebuff) MetaDefault[index];
		public static buffdebuff GetEntity(string entityName) => (buffdebuff) MetaDefault.GetEntity(entityName);
		public static buffdebuff NewEntity() => (buffdebuff) MetaDefault.NewEntity();
		public static buffdebuff NewEntity(BGId entityId) => (buffdebuff) MetaDefault.NewEntity(entityId);
		public static buffdebuff NewEntity(Action<buffdebuff> callback) => (buffdebuff) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((buffdebuff)entity)));
		public void typeId_Add(type related) => BGCodeGenUtils.MultipleRelationAdd(_typeId, Index, related);
		public void typeId_Remove(type related) => BGCodeGenUtils.MultipleRelationRemove(_typeId, Index, related);
		public List<Iono.MasterData.skill> FillRelatedskillListUsingtargetBuffIdRelation(List<Iono.MasterData.skill> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.skill>(Iono.MasterData.skill._targetBuffId, Id, result);
		public List<Iono.MasterData.skill> FillRelatedskillListUsinguserBuffIdRelation(List<Iono.MasterData.skill> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.skill>(Iono.MasterData.skill._userBuffId, Id, result);
		public List<Iono.MasterData.inventory> FillRelatedinventoryListUsingbuffdebuffIDRelation(List<Iono.MasterData.inventory> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.inventory>(Iono.MasterData.inventory._buffdebuffID, Id, result);
		public List<type> FilltypeId(List<type> result) => BGCodeGenUtils.MultipleRelationGet<type>(_typeId, Index, result);
		public static buffdebuff GetEntityByKeybuffKey(System.String buffId) => (buffdebuff) _buffKey.GetEntityByKey<System.String>(buffId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4699993827280895298UL,17438361447795262139UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4687238973632179271UL, 1864200036504196287UL));
			_ufle12jhs77_buffId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5657514695913066624UL, 6993011482850646692UL));
			_ufle12jhs77_memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5514847217024097780UL, 5213281375434653581UL));
			_ufle12jhs77_activationCondition = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4811428152361450916UL, 3550964937271853238UL));
			_ufle12jhs77_tag1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5532208521926524070UL, 2804432832839120039UL));
			_ufle12jhs77_tag2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5167644421136567475UL, 3637738721041258135UL));
			_ufle12jhs77_gender = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5490807830882938108UL, 15542905561820646529UL));
			_ufle12jhs77_activationRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4839298101478417852UL, 8425764103347763601UL));
			_ufle12jhs77_turnCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5082909908324151192UL, 11865525294893584787UL));
			_ufle12jhs77_effectTarget = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5364245553622036372UL, 176893375286428336UL));
			_ufle12jhs77_consumeTiming = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5108606903378487452UL, 8212737381671945656UL));
			_ufle12jhs77_powerUpTiming = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5417264663178438202UL, 14927538864030012055UL));
			_ufle12jhs77_maxStacks = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5070375692578368098UL, 9903950123912365490UL));
			_ufle12jhs77_buffType1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5436221321068810921UL, 9593245426072740246UL));
			_ufle12jhs77_buffValue1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5420376048428271068UL, 13682774272955766459UL));
			_ufle12jhs77_specialEffectTag1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5740474805537465056UL, 11125338150783074699UL));
			_ufle12jhs77_valueModifierType1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4617256288311391142UL, 8507679789460896139UL));
			_ufle12jhs77_typeId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(_metaDefault, new BGId(4920717210643321025UL, 3211686099010039174UL));
			_ufle12jhs77_unerasableFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5758501882099323519UL, 14829223627322287016UL));
			_edeht3sdad33_buffKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5701269069400636383UL, 4078363698253069977UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_buffId = null;
			_ufle12jhs77_memo = null;
			_ufle12jhs77_activationCondition = null;
			_ufle12jhs77_tag1 = null;
			_ufle12jhs77_tag2 = null;
			_ufle12jhs77_gender = null;
			_ufle12jhs77_activationRate = null;
			_ufle12jhs77_turnCount = null;
			_ufle12jhs77_effectTarget = null;
			_ufle12jhs77_consumeTiming = null;
			_ufle12jhs77_powerUpTiming = null;
			_ufle12jhs77_maxStacks = null;
			_ufle12jhs77_buffType1 = null;
			_ufle12jhs77_buffValue1 = null;
			_ufle12jhs77_specialEffectTag1 = null;
			_ufle12jhs77_valueModifierType1 = null;
			_ufle12jhs77_typeId = null;
			_ufle12jhs77_unerasableFlag = null;
			_edeht3sdad33_buffKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new buffdebuff(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new buffdebuff(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "buffdebuff";
			public const string name = "name";
			public const string buffId = "buffId";
			public const string memo = "memo";
			public const string activationCondition = "activationCondition";
			public const string tag1 = "tag1";
			public const string tag2 = "tag2";
			public const string gender = "gender";
			public const string activationRate = "activationRate";
			public const string turnCount = "turnCount";
			public const string effectTarget = "effectTarget";
			public const string consumeTiming = "consumeTiming";
			public const string powerUpTiming = "powerUpTiming";
			public const string maxStacks = "maxStacks";
			public const string buffType1 = "buffType1";
			public const string buffValue1 = "buffValue1";
			public const string specialEffectTag1 = "specialEffectTag1";
			public const string valueModifierType1 = "valueModifierType1";
			public const string typeId = "typeId";
			public const string unerasableFlag = "unerasableFlag";
			public const string buffKey = "buffKey";
		}
	}
}
#pragma warning restore 414
