using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public static class BGCodeGenRuntimeInitializer
	{
		[Preserve]
		public static void InitializeCodeGenRuntime()
		{
			TextMaster.InitializeCodeGenRuntime();
			playerunit.InitializeCodeGenRuntime();
		}
		[Preserve]
		public static void ReleaseCodeGenRuntime()
		{
			TextMaster.ReleaseCodeGenRuntime();
			playerunit.ReleaseCodeGenRuntime();
		}
	}
}
#pragma warning restore 414
