using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public static class BGCodeGenRuntimeInitializer
	{
		[Preserve]
		public static void InitializeCodeGenRuntime()
		{
			TextMaster.InitializeCodeGenRuntime();
			playerunit.InitializeCodeGenRuntime();
			enemyunit.InitializeCodeGenRuntime();
			enemypattern.InitializeCodeGenRuntime();
			enemyslotdetail.InitializeCodeGenRuntime();
			item.InitializeCodeGenRuntime();
			type.InitializeCodeGenRuntime();
			typeCompatibility.InitializeCodeGenRuntime();
			janken.InitializeCodeGenRuntime();
			jankenCompatibility.InitializeCodeGenRuntime();
			skill.InitializeCodeGenRuntime();
			weather.InitializeCodeGenRuntime();
			field.InitializeCodeGenRuntime();
			buffdebuff.InitializeCodeGenRuntime();
			abnormalcondition.InitializeCodeGenRuntime();
			specialeffect.InitializeCodeGenRuntime();
			inventory.InitializeCodeGenRuntime();
		}
		[Preserve]
		public static void ReleaseCodeGenRuntime()
		{
			TextMaster.ReleaseCodeGenRuntime();
			playerunit.ReleaseCodeGenRuntime();
			enemyunit.ReleaseCodeGenRuntime();
			enemypattern.ReleaseCodeGenRuntime();
			enemyslotdetail.ReleaseCodeGenRuntime();
			item.ReleaseCodeGenRuntime();
			type.ReleaseCodeGenRuntime();
			typeCompatibility.ReleaseCodeGenRuntime();
			janken.ReleaseCodeGenRuntime();
			jankenCompatibility.ReleaseCodeGenRuntime();
			skill.ReleaseCodeGenRuntime();
			weather.ReleaseCodeGenRuntime();
			field.ReleaseCodeGenRuntime();
			buffdebuff.ReleaseCodeGenRuntime();
			abnormalcondition.ReleaseCodeGenRuntime();
			specialeffect.ReleaseCodeGenRuntime();
			inventory.ReleaseCodeGenRuntime();
		}
	}
}
#pragma warning restore 414
