using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class enemypattern : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4683269916388146719UL,12783184638138125227UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String patternId
		{
			get => _patternId[Index];
			set => _patternId[Index] = value;
		}
		public System.String slotId1
		{
			get => _slotId1[Index];
			set => _slotId1[Index] = value;
		}
		public System.String slotId2
		{
			get => _slotId2[Index];
			set => _slotId2[Index] = value;
		}
		public System.String slotId3
		{
			get => _slotId3[Index];
			set => _slotId3[Index] = value;
		}
		public System.String slotId4
		{
			get => _slotId4[Index];
			set => _slotId4[Index] = value;
		}
		public System.String slotId5
		{
			get => _slotId5[Index];
			set => _slotId5[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5054006690465944213UL, 2103289283230114220UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_patternId;
		public static BansheeGz.BGDatabase.BGFieldString _patternId => _ufle12jhs77_patternId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5314139791351891301UL, 15433620926625559218UL), () => _ufle12jhs77_patternId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_slotId1;
		public static BansheeGz.BGDatabase.BGFieldString _slotId1 => _ufle12jhs77_slotId1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5272197625053160738UL, 17810516003392331704UL), () => _ufle12jhs77_slotId1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_slotId2;
		public static BansheeGz.BGDatabase.BGFieldString _slotId2 => _ufle12jhs77_slotId2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5040336070638376137UL, 5048548399650703509UL), () => _ufle12jhs77_slotId2 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_slotId3;
		public static BansheeGz.BGDatabase.BGFieldString _slotId3 => _ufle12jhs77_slotId3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5731315999852171632UL, 4576144661929661063UL), () => _ufle12jhs77_slotId3 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_slotId4;
		public static BansheeGz.BGDatabase.BGFieldString _slotId4 => _ufle12jhs77_slotId4 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5064265378050140278UL, 9849516237058494099UL), () => _ufle12jhs77_slotId4 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_slotId5;
		public static BansheeGz.BGDatabase.BGFieldString _slotId5 => _ufle12jhs77_slotId5 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5764521547746197863UL, 1808837541564457625UL), () => _ufle12jhs77_slotId5 = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_enemypatternKey;
		public static BansheeGz.BGDatabase.BGKey _enemypatternKey => _edeht3sdad33_enemypatternKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5140729650599859363UL, 8482042395841036928UL), () => _edeht3sdad33_enemypatternKey = null);
		private enemypattern() : base(MetaDefault) {}
		private enemypattern(BGId id) : base(MetaDefault, id) {}
		private enemypattern(BGMetaEntity meta) : base(meta) {}
		private enemypattern(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static enemypattern FindEntity(Predicate<enemypattern> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<enemypattern> FindEntities(Predicate<enemypattern> filter, List<enemypattern> result=null, Comparison<enemypattern> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<enemypattern> action, Predicate<enemypattern> filter=null, Comparison<enemypattern> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static enemypattern GetEntity(BGId entityId) => (enemypattern) MetaDefault.GetEntity(entityId);
		public static enemypattern GetEntity(int index) => (enemypattern) MetaDefault[index];
		public static enemypattern GetEntity(string entityName) => (enemypattern) MetaDefault.GetEntity(entityName);
		public static enemypattern NewEntity() => (enemypattern) MetaDefault.NewEntity();
		public static enemypattern NewEntity(BGId entityId) => (enemypattern) MetaDefault.NewEntity(entityId);
		public static enemypattern NewEntity(Action<enemypattern> callback) => (enemypattern) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((enemypattern)entity)));
		public static enemypattern GetEntityByKeyenemypatternKey(System.String patternId) => (enemypattern) _enemypatternKey.GetEntityByKey<System.String>(patternId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4683269916388146719UL,12783184638138125227UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5054006690465944213UL, 2103289283230114220UL));
			_ufle12jhs77_patternId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5314139791351891301UL, 15433620926625559218UL));
			_ufle12jhs77_slotId1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5272197625053160738UL, 17810516003392331704UL));
			_ufle12jhs77_slotId2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5040336070638376137UL, 5048548399650703509UL));
			_ufle12jhs77_slotId3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5731315999852171632UL, 4576144661929661063UL));
			_ufle12jhs77_slotId4 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5064265378050140278UL, 9849516237058494099UL));
			_ufle12jhs77_slotId5 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5764521547746197863UL, 1808837541564457625UL));
			_edeht3sdad33_enemypatternKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5140729650599859363UL, 8482042395841036928UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_patternId = null;
			_ufle12jhs77_slotId1 = null;
			_ufle12jhs77_slotId2 = null;
			_ufle12jhs77_slotId3 = null;
			_ufle12jhs77_slotId4 = null;
			_ufle12jhs77_slotId5 = null;
			_edeht3sdad33_enemypatternKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new enemypattern(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new enemypattern(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "enemypattern";
			public const string name = "name";
			public const string patternId = "patternId";
			public const string slotId1 = "slotId1";
			public const string slotId2 = "slotId2";
			public const string slotId3 = "slotId3";
			public const string slotId4 = "slotId4";
			public const string slotId5 = "slotId5";
			public const string enemypatternKey = "enemypatternKey";
		}
	}
}
#pragma warning restore 414
