using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class enemypattern : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4683269916388146719UL,12783184638138125227UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String patternId
		{
			get => _patternId[Index];
			set => _patternId[Index] = value;
		}
		public enemyslotdetail slotId_1
		{
			get => (enemyslotdetail) _slotId_1[Index];
			set => _slotId_1[Index] = value;
		}
		public enemyslotdetail slotId_2
		{
			get => (enemyslotdetail) _slotId_2[Index];
			set => _slotId_2[Index] = value;
		}
		public enemyslotdetail slotId_3
		{
			get => (enemyslotdetail) _slotId_3[Index];
			set => _slotId_3[Index] = value;
		}
		public enemyslotdetail slotId_4
		{
			get => (enemyslotdetail) _slotId_4[Index];
			set => _slotId_4[Index] = value;
		}
		public enemyslotdetail slotId_5
		{
			get => (enemyslotdetail) _slotId_5[Index];
			set => _slotId_5[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5054006690465944213UL, 2103289283230114220UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_patternId;
		public static BansheeGz.BGDatabase.BGFieldString _patternId => _ufle12jhs77_patternId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5314139791351891301UL, 15433620926625559218UL), () => _ufle12jhs77_patternId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_slotId_1;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _slotId_1 => _ufle12jhs77_slotId_1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4845496413181159889UL, 8192884728923098784UL), () => _ufle12jhs77_slotId_1 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_slotId_2;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _slotId_2 => _ufle12jhs77_slotId_2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5036480768525269577UL, 10073718330858388145UL), () => _ufle12jhs77_slotId_2 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_slotId_3;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _slotId_3 => _ufle12jhs77_slotId_3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5299643496424202406UL, 16644882907035634584UL), () => _ufle12jhs77_slotId_3 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_slotId_4;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _slotId_4 => _ufle12jhs77_slotId_4 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5017287404188695285UL, 1480588218231687335UL), () => _ufle12jhs77_slotId_4 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_slotId_5;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _slotId_5 => _ufle12jhs77_slotId_5 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5675230138247866535UL, 16428072515844839821UL), () => _ufle12jhs77_slotId_5 = null);
		public List<Iono.MasterData.enemyunit> RelatedenemyunitListUsingpatternId1Relation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyunit>(Iono.MasterData.enemyunit._patternId1, Id);
		public List<Iono.MasterData.enemyunit> RelatedenemyunitListUsingpatternId2Relation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyunit>(Iono.MasterData.enemyunit._patternId2, Id);
		public List<Iono.MasterData.enemyunit> RelatedenemyunitListUsingpatternId3Relation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyunit>(Iono.MasterData.enemyunit._patternId3, Id);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_enemypatternKey;
		public static BansheeGz.BGDatabase.BGKey _enemypatternKey => _edeht3sdad33_enemypatternKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5140729650599859363UL, 8482042395841036928UL), () => _edeht3sdad33_enemypatternKey = null);
		private enemypattern() : base(MetaDefault) {}
		private enemypattern(BGId id) : base(MetaDefault, id) {}
		private enemypattern(BGMetaEntity meta) : base(meta) {}
		private enemypattern(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static enemypattern FindEntity(Predicate<enemypattern> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<enemypattern> FindEntities(Predicate<enemypattern> filter, List<enemypattern> result=null, Comparison<enemypattern> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<enemypattern> action, Predicate<enemypattern> filter=null, Comparison<enemypattern> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static enemypattern GetEntity(BGId entityId) => (enemypattern) MetaDefault.GetEntity(entityId);
		public static enemypattern GetEntity(int index) => (enemypattern) MetaDefault[index];
		public static enemypattern GetEntity(string entityName) => (enemypattern) MetaDefault.GetEntity(entityName);
		public static enemypattern NewEntity() => (enemypattern) MetaDefault.NewEntity();
		public static enemypattern NewEntity(BGId entityId) => (enemypattern) MetaDefault.NewEntity(entityId);
		public static enemypattern NewEntity(Action<enemypattern> callback) => (enemypattern) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((enemypattern)entity)));
		public List<Iono.MasterData.enemyunit> FillRelatedenemyunitListUsingpatternId1Relation(List<Iono.MasterData.enemyunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyunit>(Iono.MasterData.enemyunit._patternId1, Id, result);
		public List<Iono.MasterData.enemyunit> FillRelatedenemyunitListUsingpatternId2Relation(List<Iono.MasterData.enemyunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyunit>(Iono.MasterData.enemyunit._patternId2, Id, result);
		public List<Iono.MasterData.enemyunit> FillRelatedenemyunitListUsingpatternId3Relation(List<Iono.MasterData.enemyunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyunit>(Iono.MasterData.enemyunit._patternId3, Id, result);
		public static enemypattern GetEntityByKeyenemypatternKey(System.String patternId) => (enemypattern) _enemypatternKey.GetEntityByKey<System.String>(patternId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4683269916388146719UL,12783184638138125227UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5054006690465944213UL, 2103289283230114220UL));
			_ufle12jhs77_patternId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5314139791351891301UL, 15433620926625559218UL));
			_ufle12jhs77_slotId_1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4845496413181159889UL, 8192884728923098784UL));
			_ufle12jhs77_slotId_2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5036480768525269577UL, 10073718330858388145UL));
			_ufle12jhs77_slotId_3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5299643496424202406UL, 16644882907035634584UL));
			_ufle12jhs77_slotId_4 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5017287404188695285UL, 1480588218231687335UL));
			_ufle12jhs77_slotId_5 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5675230138247866535UL, 16428072515844839821UL));
			_edeht3sdad33_enemypatternKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5140729650599859363UL, 8482042395841036928UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_patternId = null;
			_ufle12jhs77_slotId_1 = null;
			_ufle12jhs77_slotId_2 = null;
			_ufle12jhs77_slotId_3 = null;
			_ufle12jhs77_slotId_4 = null;
			_ufle12jhs77_slotId_5 = null;
			_edeht3sdad33_enemypatternKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new enemypattern(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new enemypattern(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "enemypattern";
			public const string name = "name";
			public const string patternId = "patternId";
			public const string slotId_1 = "slotId_1";
			public const string slotId_2 = "slotId_2";
			public const string slotId_3 = "slotId_3";
			public const string slotId_4 = "slotId_4";
			public const string slotId_5 = "slotId_5";
			public const string enemypatternKey = "enemypatternKey";
		}
	}
}
#pragma warning restore 414
