using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class enemyunit : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5196248222067569656UL,14895870581277299105UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String enemyId
		{
			get => _enemyId[Index];
			set => _enemyId[Index] = value;
		}
		public System.String nameTextId
		{
			get => _nameTextId[Index];
			set => _nameTextId[Index] = value;
		}
		public System.String descTextId
		{
			get => _descTextId[Index];
			set => _descTextId[Index] = value;
		}
		public System.String memo
		{
			get => _memo[Index];
			set => _memo[Index] = value;
		}
		public System.String imageId
		{
			get => _imageId[Index];
			set => _imageId[Index] = value;
		}
		public System.String gender
		{
			get => _gender[Index];
			set => _gender[Index] = value;
		}
		public System.Int32 hp
		{
			get => _hp[Index];
			set => _hp.SetValue(this, value);
		}
		public System.Int32 atk
		{
			get => _atk[Index];
			set => _atk.SetValue(this, value);
		}
		public System.Int32 def
		{
			get => _def[Index];
			set => _def.SetValue(this, value);
		}
		public System.Int32 spAtk
		{
			get => _spAtk[Index];
			set => _spAtk.SetValue(this, value);
		}
		public System.Int32 spDef
		{
			get => _spDef[Index];
			set => _spDef.SetValue(this, value);
		}
		public System.Int32 spd
		{
			get => _spd[Index];
			set => _spd.SetValue(this, value);
		}
		public System.Int32 resPoison
		{
			get => _resPoison[Index];
			set => _resPoison.SetValue(this, value);
		}
		public System.Int32 resSleep
		{
			get => _resSleep[Index];
			set => _resSleep.SetValue(this, value);
		}
		public System.Int32 resParalysis
		{
			get => _resParalysis[Index];
			set => _resParalysis.SetValue(this, value);
		}
		public System.Int32 resConfusion
		{
			get => _resConfusion[Index];
			set => _resConfusion.SetValue(this, value);
		}
		public System.String tag1
		{
			get => _tag1[Index];
			set => _tag1[Index] = value;
		}
		public System.String tag2
		{
			get => _tag2[Index];
			set => _tag2[Index] = value;
		}
		public System.Int32 nWincount
		{
			get => _nWincount[Index];
			set => _nWincount.SetValue(this, value);
		}
		public type typeId
		{
			get => (type) _typeId[Index];
			set => _typeId[Index] = value;
		}
		public skill passiveSkillId
		{
			get => (skill) _passiveSkillId[Index];
			set => _passiveSkillId[Index] = value;
		}
		public enemypattern patternId1
		{
			get => (enemypattern) _patternId1[Index];
			set => _patternId1[Index] = value;
		}
		public enemypattern patternId2
		{
			get => (enemypattern) _patternId2[Index];
			set => _patternId2[Index] = value;
		}
		public enemypattern patternId3
		{
			get => (enemypattern) _patternId3[Index];
			set => _patternId3[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5141801515486244407UL, 7825536873107572116UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_enemyId;
		public static BansheeGz.BGDatabase.BGFieldString _enemyId => _ufle12jhs77_enemyId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5301623826041389310UL, 5860836552745697174UL), () => _ufle12jhs77_enemyId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_nameTextId;
		public static BansheeGz.BGDatabase.BGFieldString _nameTextId => _ufle12jhs77_nameTextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5272559590646442526UL, 12400811507328982922UL), () => _ufle12jhs77_nameTextId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_descTextId;
		public static BansheeGz.BGDatabase.BGFieldString _descTextId => _ufle12jhs77_descTextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5188513635880496321UL, 15305111795263834035UL), () => _ufle12jhs77_descTextId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_memo;
		public static BansheeGz.BGDatabase.BGFieldString _memo => _ufle12jhs77_memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5034598974033327329UL, 227121275910717825UL), () => _ufle12jhs77_memo = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_imageId;
		public static BansheeGz.BGDatabase.BGFieldString _imageId => _ufle12jhs77_imageId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4943565377203862859UL, 1978886953351121046UL), () => _ufle12jhs77_imageId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_gender;
		public static BansheeGz.BGDatabase.BGFieldString _gender => _ufle12jhs77_gender ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5625313432302987723UL, 4096865780255537585UL), () => _ufle12jhs77_gender = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
		public static BansheeGz.BGDatabase.BGFieldInt _hp => _ufle12jhs77_hp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5335272925889909868UL, 8996922719802329274UL), () => _ufle12jhs77_hp = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
		public static BansheeGz.BGDatabase.BGFieldInt _atk => _ufle12jhs77_atk ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5071019117707825172UL, 6623356890067510409UL), () => _ufle12jhs77_atk = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_def;
		public static BansheeGz.BGDatabase.BGFieldInt _def => _ufle12jhs77_def ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4775146271363402833UL, 7594620381264106626UL), () => _ufle12jhs77_def = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_spAtk;
		public static BansheeGz.BGDatabase.BGFieldInt _spAtk => _ufle12jhs77_spAtk ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5747281539479083226UL, 7930849096879818885UL), () => _ufle12jhs77_spAtk = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_spDef;
		public static BansheeGz.BGDatabase.BGFieldInt _spDef => _ufle12jhs77_spDef ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5629114061780003892UL, 3849279279414130082UL), () => _ufle12jhs77_spDef = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_spd;
		public static BansheeGz.BGDatabase.BGFieldInt _spd => _ufle12jhs77_spd ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5611407386121945893UL, 2298752444022027700UL), () => _ufle12jhs77_spd = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_resPoison;
		public static BansheeGz.BGDatabase.BGFieldInt _resPoison => _ufle12jhs77_resPoison ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4969790692561375783UL, 11799386321779570862UL), () => _ufle12jhs77_resPoison = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_resSleep;
		public static BansheeGz.BGDatabase.BGFieldInt _resSleep => _ufle12jhs77_resSleep ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5100229908391376163UL, 11029896516071531426UL), () => _ufle12jhs77_resSleep = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_resParalysis;
		public static BansheeGz.BGDatabase.BGFieldInt _resParalysis => _ufle12jhs77_resParalysis ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4793450035303321863UL, 16213589791402727325UL), () => _ufle12jhs77_resParalysis = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_resConfusion;
		public static BansheeGz.BGDatabase.BGFieldInt _resConfusion => _ufle12jhs77_resConfusion ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4724570924791986257UL, 13527957130585592989UL), () => _ufle12jhs77_resConfusion = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_tag1;
		public static BansheeGz.BGDatabase.BGFieldString _tag1 => _ufle12jhs77_tag1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5532998002609912316UL, 196760643606742412UL), () => _ufle12jhs77_tag1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_tag2;
		public static BansheeGz.BGDatabase.BGFieldString _tag2 => _ufle12jhs77_tag2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5742669554728063558UL, 9840451198634888591UL), () => _ufle12jhs77_tag2 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_nWincount;
		public static BansheeGz.BGDatabase.BGFieldInt _nWincount => _ufle12jhs77_nWincount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4890149416489459488UL, 7701179678101878934UL), () => _ufle12jhs77_nWincount = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_typeId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _typeId => _ufle12jhs77_typeId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5006314466140802145UL, 13546037775822006420UL), () => _ufle12jhs77_typeId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_passiveSkillId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _passiveSkillId => _ufle12jhs77_passiveSkillId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5594680660547506182UL, 7411147513732158139UL), () => _ufle12jhs77_passiveSkillId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_patternId1;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _patternId1 => _ufle12jhs77_patternId1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5452403331052459873UL, 11993180790882645638UL), () => _ufle12jhs77_patternId1 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_patternId2;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _patternId2 => _ufle12jhs77_patternId2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4865759233001546679UL, 5218297205876646829UL), () => _ufle12jhs77_patternId2 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_patternId3;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _patternId3 => _ufle12jhs77_patternId3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5228159484620751656UL, 7852049258246782868UL), () => _ufle12jhs77_patternId3 = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_enemyKey;
		public static BansheeGz.BGDatabase.BGKey _enemyKey => _edeht3sdad33_enemyKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(4925184542210416332UL, 4874785857179485868UL), () => _edeht3sdad33_enemyKey = null);
		private enemyunit() : base(MetaDefault) {}
		private enemyunit(BGId id) : base(MetaDefault, id) {}
		private enemyunit(BGMetaEntity meta) : base(meta) {}
		private enemyunit(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static enemyunit FindEntity(Predicate<enemyunit> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<enemyunit> FindEntities(Predicate<enemyunit> filter, List<enemyunit> result=null, Comparison<enemyunit> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<enemyunit> action, Predicate<enemyunit> filter=null, Comparison<enemyunit> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static enemyunit GetEntity(BGId entityId) => (enemyunit) MetaDefault.GetEntity(entityId);
		public static enemyunit GetEntity(int index) => (enemyunit) MetaDefault[index];
		public static enemyunit GetEntity(string entityName) => (enemyunit) MetaDefault.GetEntity(entityName);
		public static enemyunit NewEntity() => (enemyunit) MetaDefault.NewEntity();
		public static enemyunit NewEntity(BGId entityId) => (enemyunit) MetaDefault.NewEntity(entityId);
		public static enemyunit NewEntity(Action<enemyunit> callback) => (enemyunit) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((enemyunit)entity)));
		public static enemyunit GetEntityByKeyenemyKey(System.String enemyId) => (enemyunit) _enemyKey.GetEntityByKey<System.String>(enemyId);
		public static List<enemyunit> GetEntitiesByKeyenemyKey(System.String enemyId, List<enemyunit> result=null) => _enemyKey.GetEntitiesByKey<enemyunit, System.String>(result, enemyId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5196248222067569656UL,14895870581277299105UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5141801515486244407UL, 7825536873107572116UL));
			_ufle12jhs77_enemyId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5301623826041389310UL, 5860836552745697174UL));
			_ufle12jhs77_nameTextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5272559590646442526UL, 12400811507328982922UL));
			_ufle12jhs77_descTextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5188513635880496321UL, 15305111795263834035UL));
			_ufle12jhs77_memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5034598974033327329UL, 227121275910717825UL));
			_ufle12jhs77_imageId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4943565377203862859UL, 1978886953351121046UL));
			_ufle12jhs77_gender = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5625313432302987723UL, 4096865780255537585UL));
			_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5335272925889909868UL, 8996922719802329274UL));
			_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5071019117707825172UL, 6623356890067510409UL));
			_ufle12jhs77_def = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4775146271363402833UL, 7594620381264106626UL));
			_ufle12jhs77_spAtk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5747281539479083226UL, 7930849096879818885UL));
			_ufle12jhs77_spDef = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5629114061780003892UL, 3849279279414130082UL));
			_ufle12jhs77_spd = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5611407386121945893UL, 2298752444022027700UL));
			_ufle12jhs77_resPoison = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4969790692561375783UL, 11799386321779570862UL));
			_ufle12jhs77_resSleep = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5100229908391376163UL, 11029896516071531426UL));
			_ufle12jhs77_resParalysis = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4793450035303321863UL, 16213589791402727325UL));
			_ufle12jhs77_resConfusion = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4724570924791986257UL, 13527957130585592989UL));
			_ufle12jhs77_tag1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5532998002609912316UL, 196760643606742412UL));
			_ufle12jhs77_tag2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5742669554728063558UL, 9840451198634888591UL));
			_ufle12jhs77_nWincount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4890149416489459488UL, 7701179678101878934UL));
			_ufle12jhs77_typeId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5006314466140802145UL, 13546037775822006420UL));
			_ufle12jhs77_passiveSkillId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5594680660547506182UL, 7411147513732158139UL));
			_ufle12jhs77_patternId1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5452403331052459873UL, 11993180790882645638UL));
			_ufle12jhs77_patternId2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4865759233001546679UL, 5218297205876646829UL));
			_ufle12jhs77_patternId3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5228159484620751656UL, 7852049258246782868UL));
			_edeht3sdad33_enemyKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(4925184542210416332UL, 4874785857179485868UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_enemyId = null;
			_ufle12jhs77_nameTextId = null;
			_ufle12jhs77_descTextId = null;
			_ufle12jhs77_memo = null;
			_ufle12jhs77_imageId = null;
			_ufle12jhs77_gender = null;
			_ufle12jhs77_hp = null;
			_ufle12jhs77_atk = null;
			_ufle12jhs77_def = null;
			_ufle12jhs77_spAtk = null;
			_ufle12jhs77_spDef = null;
			_ufle12jhs77_spd = null;
			_ufle12jhs77_resPoison = null;
			_ufle12jhs77_resSleep = null;
			_ufle12jhs77_resParalysis = null;
			_ufle12jhs77_resConfusion = null;
			_ufle12jhs77_tag1 = null;
			_ufle12jhs77_tag2 = null;
			_ufle12jhs77_nWincount = null;
			_ufle12jhs77_typeId = null;
			_ufle12jhs77_passiveSkillId = null;
			_ufle12jhs77_patternId1 = null;
			_ufle12jhs77_patternId2 = null;
			_ufle12jhs77_patternId3 = null;
			_edeht3sdad33_enemyKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new enemyunit(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new enemyunit(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "enemyunit";
			public const string name = "name";
			public const string enemyId = "enemyId";
			public const string nameTextId = "nameTextId";
			public const string descTextId = "descTextId";
			public const string memo = "memo";
			public const string imageId = "imageId";
			public const string gender = "gender";
			public const string hp = "hp";
			public const string atk = "atk";
			public const string def = "def";
			public const string spAtk = "spAtk";
			public const string spDef = "spDef";
			public const string spd = "spd";
			public const string resPoison = "resPoison";
			public const string resSleep = "resSleep";
			public const string resParalysis = "resParalysis";
			public const string resConfusion = "resConfusion";
			public const string tag1 = "tag1";
			public const string tag2 = "tag2";
			public const string nWincount = "nWincount";
			public const string typeId = "typeId";
			public const string passiveSkillId = "passiveSkillId";
			public const string patternId1 = "patternId1";
			public const string patternId2 = "patternId2";
			public const string patternId3 = "patternId3";
			public const string enemyKey = "enemyKey";
		}
	}
}
#pragma warning restore 414
