using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class enemyslotdetail : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5348329999930997860UL,17449553450287559326UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String skillId
		{
			get => _skillId[Index];
			set => _skillId[Index] = value;
		}
		public System.String memo
		{
			get => _memo[Index];
			set => _memo[Index] = value;
		}
		public System.String reconFlagId
		{
			get => _reconFlagId[Index];
			set => _reconFlagId[Index] = value;
		}
		public System.String enemyslotId
		{
			get => _enemyslotId[Index];
			set => _enemyslotId[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5402286177552199299UL, 6733892289240205443UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillId;
		public static BansheeGz.BGDatabase.BGFieldString _skillId => _ufle12jhs77_skillId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5734644989201530749UL, 15225169235875993235UL), () => _ufle12jhs77_skillId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_memo;
		public static BansheeGz.BGDatabase.BGFieldString _memo => _ufle12jhs77_memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5520669255016850248UL, 17413153774078563485UL), () => _ufle12jhs77_memo = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_reconFlagId;
		public static BansheeGz.BGDatabase.BGFieldString _reconFlagId => _ufle12jhs77_reconFlagId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5577011547542091596UL, 18305501518055447230UL), () => _ufle12jhs77_reconFlagId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_enemyslotId;
		public static BansheeGz.BGDatabase.BGFieldString _enemyslotId => _ufle12jhs77_enemyslotId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5241983390952653641UL, 14615359806695301039UL), () => _ufle12jhs77_enemyslotId = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_enemyslotKey;
		public static BansheeGz.BGDatabase.BGKey _enemyslotKey => _edeht3sdad33_enemyslotKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5440094805292329809UL, 17585278008490142UL), () => _edeht3sdad33_enemyslotKey = null);
		private enemyslotdetail() : base(MetaDefault) {}
		private enemyslotdetail(BGId id) : base(MetaDefault, id) {}
		private enemyslotdetail(BGMetaEntity meta) : base(meta) {}
		private enemyslotdetail(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static enemyslotdetail FindEntity(Predicate<enemyslotdetail> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<enemyslotdetail> FindEntities(Predicate<enemyslotdetail> filter, List<enemyslotdetail> result=null, Comparison<enemyslotdetail> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<enemyslotdetail> action, Predicate<enemyslotdetail> filter=null, Comparison<enemyslotdetail> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static enemyslotdetail GetEntity(BGId entityId) => (enemyslotdetail) MetaDefault.GetEntity(entityId);
		public static enemyslotdetail GetEntity(int index) => (enemyslotdetail) MetaDefault[index];
		public static enemyslotdetail GetEntity(string entityName) => (enemyslotdetail) MetaDefault.GetEntity(entityName);
		public static enemyslotdetail NewEntity() => (enemyslotdetail) MetaDefault.NewEntity();
		public static enemyslotdetail NewEntity(BGId entityId) => (enemyslotdetail) MetaDefault.NewEntity(entityId);
		public static enemyslotdetail NewEntity(Action<enemyslotdetail> callback) => (enemyslotdetail) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((enemyslotdetail)entity)));
		public static enemyslotdetail GetEntityByKeyenemyslotKey(System.String enemyslotId) => (enemyslotdetail) _enemyslotKey.GetEntityByKey<System.String>(enemyslotId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5348329999930997860UL,17449553450287559326UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5402286177552199299UL, 6733892289240205443UL));
			_ufle12jhs77_skillId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5734644989201530749UL, 15225169235875993235UL));
			_ufle12jhs77_memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5520669255016850248UL, 17413153774078563485UL));
			_ufle12jhs77_reconFlagId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5577011547542091596UL, 18305501518055447230UL));
			_ufle12jhs77_enemyslotId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5241983390952653641UL, 14615359806695301039UL));
			_edeht3sdad33_enemyslotKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5440094805292329809UL, 17585278008490142UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_skillId = null;
			_ufle12jhs77_memo = null;
			_ufle12jhs77_reconFlagId = null;
			_ufle12jhs77_enemyslotId = null;
			_edeht3sdad33_enemyslotKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new enemyslotdetail(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new enemyslotdetail(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "enemyslotdetail";
			public const string name = "name";
			public const string skillId = "skillId";
			public const string memo = "memo";
			public const string reconFlagId = "reconFlagId";
			public const string enemyslotId = "enemyslotId";
			public const string enemyslotKey = "enemyslotKey";
		}
	}
}
#pragma warning restore 414
