using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class field : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4807071390928795343UL,12998800758083226760UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String fieldId
		{
			get => _fieldId[Index];
			set => _fieldId[Index] = value;
		}
		public System.String memo
		{
			get => _memo[Index];
			set => _memo[Index] = value;
		}
		public System.String preventOverwriteFlag
		{
			get => _preventOverwriteFlag[Index];
			set => _preventOverwriteFlag[Index] = value;
		}
		public System.Int32 duration
		{
			get => _duration[Index];
			set => _duration.SetValue(this, value);
		}
		public System.Int32 healEndTurnRate
		{
			get => _healEndTurnRate[Index];
			set => _healEndTurnRate.SetValue(this, value);
		}
		public System.Int32 plusDamageRate
		{
			get => _plusDamageRate[Index];
			set => _plusDamageRate.SetValue(this, value);
		}
		public System.Int32 minusDamageRate
		{
			get => _minusDamageRate[Index];
			set => _minusDamageRate.SetValue(this, value);
		}
		public type plusDamageTypeId
		{
			get => (type) _plusDamageTypeId[Index];
			set => _plusDamageTypeId[Index] = value;
		}
		public type minusDamageTypeId
		{
			get => (type) _minusDamageTypeId[Index];
			set => _minusDamageTypeId[Index] = value;
		}
		public skill negatedSkillId
		{
			get => (skill) _negatedSkillId[Index];
			set => _negatedSkillId[Index] = value;
		}
		public System.Boolean preventPriorityFlag
		{
			get => _preventPriorityFlag[Index];
			set => _preventPriorityFlag.SetValue(this, value);
		}
		public abnormalcondition negatedConditionId
		{
			get => (abnormalcondition) _negatedConditionId[Index];
			set => _negatedConditionId[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5064983754645516911UL, 7615715515282199704UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_fieldId;
		public static BansheeGz.BGDatabase.BGFieldString _fieldId => _ufle12jhs77_fieldId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5052992277415422418UL, 13989648592115498923UL), () => _ufle12jhs77_fieldId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_memo;
		public static BansheeGz.BGDatabase.BGFieldString _memo => _ufle12jhs77_memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5396161896030477841UL, 17183565430326180017UL), () => _ufle12jhs77_memo = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_preventOverwriteFlag;
		public static BansheeGz.BGDatabase.BGFieldString _preventOverwriteFlag => _ufle12jhs77_preventOverwriteFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5559669755363994355UL, 2321956138862408629UL), () => _ufle12jhs77_preventOverwriteFlag = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_duration;
		public static BansheeGz.BGDatabase.BGFieldInt _duration => _ufle12jhs77_duration ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4881380040841939859UL, 2582038382285249197UL), () => _ufle12jhs77_duration = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_healEndTurnRate;
		public static BansheeGz.BGDatabase.BGFieldInt _healEndTurnRate => _ufle12jhs77_healEndTurnRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5373650712912618957UL, 16425804466937573558UL), () => _ufle12jhs77_healEndTurnRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_plusDamageRate;
		public static BansheeGz.BGDatabase.BGFieldInt _plusDamageRate => _ufle12jhs77_plusDamageRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4839448979604091462UL, 7636501102453398691UL), () => _ufle12jhs77_plusDamageRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_minusDamageRate;
		public static BansheeGz.BGDatabase.BGFieldInt _minusDamageRate => _ufle12jhs77_minusDamageRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5104399102913584921UL, 17592322940615614619UL), () => _ufle12jhs77_minusDamageRate = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_plusDamageTypeId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _plusDamageTypeId => _ufle12jhs77_plusDamageTypeId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5425455208129366930UL, 2200675816792832447UL), () => _ufle12jhs77_plusDamageTypeId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_minusDamageTypeId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _minusDamageTypeId => _ufle12jhs77_minusDamageTypeId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5104544541372448170UL, 15471963993653893295UL), () => _ufle12jhs77_minusDamageTypeId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_negatedSkillId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _negatedSkillId => _ufle12jhs77_negatedSkillId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5081710980470368000UL, 7259061907990057887UL), () => _ufle12jhs77_negatedSkillId = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_preventPriorityFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _preventPriorityFlag => _ufle12jhs77_preventPriorityFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5468148211208613571UL, 4972767562889941896UL), () => _ufle12jhs77_preventPriorityFlag = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_negatedConditionId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _negatedConditionId => _ufle12jhs77_negatedConditionId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5744027725360184067UL, 4093649725294174127UL), () => _ufle12jhs77_negatedConditionId = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_fieldKey;
		public static BansheeGz.BGDatabase.BGKey _fieldKey => _edeht3sdad33_fieldKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(4957815438075259119UL, 4844997023473008270UL), () => _edeht3sdad33_fieldKey = null);
		private field() : base(MetaDefault) {}
		private field(BGId id) : base(MetaDefault, id) {}
		private field(BGMetaEntity meta) : base(meta) {}
		private field(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static field FindEntity(Predicate<field> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<field> FindEntities(Predicate<field> filter, List<field> result=null, Comparison<field> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<field> action, Predicate<field> filter=null, Comparison<field> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static field GetEntity(BGId entityId) => (field) MetaDefault.GetEntity(entityId);
		public static field GetEntity(int index) => (field) MetaDefault[index];
		public static field GetEntity(string entityName) => (field) MetaDefault.GetEntity(entityName);
		public static field NewEntity() => (field) MetaDefault.NewEntity();
		public static field NewEntity(BGId entityId) => (field) MetaDefault.NewEntity(entityId);
		public static field NewEntity(Action<field> callback) => (field) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((field)entity)));
		public static field GetEntityByKeyfieldKey(System.String fieldId) => (field) _fieldKey.GetEntityByKey<System.String>(fieldId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4807071390928795343UL,12998800758083226760UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5064983754645516911UL, 7615715515282199704UL));
			_ufle12jhs77_fieldId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5052992277415422418UL, 13989648592115498923UL));
			_ufle12jhs77_memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5396161896030477841UL, 17183565430326180017UL));
			_ufle12jhs77_preventOverwriteFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5559669755363994355UL, 2321956138862408629UL));
			_ufle12jhs77_duration = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4881380040841939859UL, 2582038382285249197UL));
			_ufle12jhs77_healEndTurnRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5373650712912618957UL, 16425804466937573558UL));
			_ufle12jhs77_plusDamageRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4839448979604091462UL, 7636501102453398691UL));
			_ufle12jhs77_minusDamageRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5104399102913584921UL, 17592322940615614619UL));
			_ufle12jhs77_plusDamageTypeId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5425455208129366930UL, 2200675816792832447UL));
			_ufle12jhs77_minusDamageTypeId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5104544541372448170UL, 15471963993653893295UL));
			_ufle12jhs77_negatedSkillId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5081710980470368000UL, 7259061907990057887UL));
			_ufle12jhs77_preventPriorityFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5468148211208613571UL, 4972767562889941896UL));
			_ufle12jhs77_negatedConditionId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5744027725360184067UL, 4093649725294174127UL));
			_edeht3sdad33_fieldKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(4957815438075259119UL, 4844997023473008270UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_fieldId = null;
			_ufle12jhs77_memo = null;
			_ufle12jhs77_preventOverwriteFlag = null;
			_ufle12jhs77_duration = null;
			_ufle12jhs77_healEndTurnRate = null;
			_ufle12jhs77_plusDamageRate = null;
			_ufle12jhs77_minusDamageRate = null;
			_ufle12jhs77_plusDamageTypeId = null;
			_ufle12jhs77_minusDamageTypeId = null;
			_ufle12jhs77_negatedSkillId = null;
			_ufle12jhs77_preventPriorityFlag = null;
			_ufle12jhs77_negatedConditionId = null;
			_edeht3sdad33_fieldKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new field(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new field(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "field";
			public const string name = "name";
			public const string fieldId = "fieldId";
			public const string memo = "memo";
			public const string preventOverwriteFlag = "preventOverwriteFlag";
			public const string duration = "duration";
			public const string healEndTurnRate = "healEndTurnRate";
			public const string plusDamageRate = "plusDamageRate";
			public const string minusDamageRate = "minusDamageRate";
			public const string plusDamageTypeId = "plusDamageTypeId";
			public const string minusDamageTypeId = "minusDamageTypeId";
			public const string negatedSkillId = "negatedSkillId";
			public const string preventPriorityFlag = "preventPriorityFlag";
			public const string negatedConditionId = "negatedConditionId";
			public const string fieldKey = "fieldKey";
		}
	}
}
#pragma warning restore 414
