using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class inventory : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5553718010987705996UL,6294421796861238146UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String inventoryId
		{
			get => _inventoryId[Index];
			set => _inventoryId[Index] = value;
		}
		public buffdebuff buffdebuffID
		{
			get => (buffdebuff) _buffdebuffID[Index];
			set => _buffdebuffID[Index] = value;
		}
		public specialeffect spEffectId
		{
			get => (specialeffect) _spEffectId[Index];
			set => _spEffectId[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4654824565030354278UL, 2602481035487726756UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_inventoryId;
		public static BansheeGz.BGDatabase.BGFieldString _inventoryId => _ufle12jhs77_inventoryId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4665131345124014195UL, 6512477414582910860UL), () => _ufle12jhs77_inventoryId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_buffdebuffID;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _buffdebuffID => _ufle12jhs77_buffdebuffID ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4798443453758431154UL, 5826394485201712009UL), () => _ufle12jhs77_buffdebuffID = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_spEffectId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _spEffectId => _ufle12jhs77_spEffectId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5054357348347325446UL, 3368679905114977936UL), () => _ufle12jhs77_spEffectId = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_inventoryKey;
		public static BansheeGz.BGDatabase.BGKey _inventoryKey => _edeht3sdad33_inventoryKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(4869735419969981185UL, 15735105706799078842UL), () => _edeht3sdad33_inventoryKey = null);
		private inventory() : base(MetaDefault) {}
		private inventory(BGId id) : base(MetaDefault, id) {}
		private inventory(BGMetaEntity meta) : base(meta) {}
		private inventory(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static inventory FindEntity(Predicate<inventory> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<inventory> FindEntities(Predicate<inventory> filter, List<inventory> result=null, Comparison<inventory> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<inventory> action, Predicate<inventory> filter=null, Comparison<inventory> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static inventory GetEntity(BGId entityId) => (inventory) MetaDefault.GetEntity(entityId);
		public static inventory GetEntity(int index) => (inventory) MetaDefault[index];
		public static inventory GetEntity(string entityName) => (inventory) MetaDefault.GetEntity(entityName);
		public static inventory NewEntity() => (inventory) MetaDefault.NewEntity();
		public static inventory NewEntity(BGId entityId) => (inventory) MetaDefault.NewEntity(entityId);
		public static inventory NewEntity(Action<inventory> callback) => (inventory) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((inventory)entity)));
		public static inventory GetEntityByKeyinventoryKey(System.String inventoryId) => (inventory) _inventoryKey.GetEntityByKey<System.String>(inventoryId);
		public static List<inventory> GetEntitiesByKeyinventoryKey(System.String inventoryId, List<inventory> result=null) => _inventoryKey.GetEntitiesByKey<inventory, System.String>(result, inventoryId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5553718010987705996UL,6294421796861238146UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4654824565030354278UL, 2602481035487726756UL));
			_ufle12jhs77_inventoryId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4665131345124014195UL, 6512477414582910860UL));
			_ufle12jhs77_buffdebuffID = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4798443453758431154UL, 5826394485201712009UL));
			_ufle12jhs77_spEffectId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5054357348347325446UL, 3368679905114977936UL));
			_edeht3sdad33_inventoryKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(4869735419969981185UL, 15735105706799078842UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_inventoryId = null;
			_ufle12jhs77_buffdebuffID = null;
			_ufle12jhs77_spEffectId = null;
			_edeht3sdad33_inventoryKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new inventory(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new inventory(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "inventory";
			public const string name = "name";
			public const string inventoryId = "inventoryId";
			public const string buffdebuffID = "buffdebuffID";
			public const string spEffectId = "spEffectId";
			public const string inventoryKey = "inventoryKey";
		}
	}
}
#pragma warning restore 414
