using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class item : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5062203024016324111UL,13564969964457416608UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String itemId
		{
			get => _itemId[Index];
			set => _itemId[Index] = value;
		}
		public System.String nameTextId
		{
			get => _nameTextId[Index];
			set => _nameTextId[Index] = value;
		}
		public System.String descTextId
		{
			get => _descTextId[Index];
			set => _descTextId[Index] = value;
		}
		public System.String imageId
		{
			get => _imageId[Index];
			set => _imageId[Index] = value;
		}
		public System.String rarity
		{
			get => _rarity[Index];
			set => _rarity[Index] = value;
		}
		public System.String skillId
		{
			get => _skillId[Index];
			set => _skillId[Index] = value;
		}
		public System.String itemCategory
		{
			get => _itemCategory[Index];
			set => _itemCategory[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5021313763942901040UL, 3028225332249866880UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_itemId;
		public static BansheeGz.BGDatabase.BGFieldString _itemId => _ufle12jhs77_itemId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5711455164051416651UL, 1298899124958642566UL), () => _ufle12jhs77_itemId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_nameTextId;
		public static BansheeGz.BGDatabase.BGFieldString _nameTextId => _ufle12jhs77_nameTextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4729552418832784748UL, 8956478432743926673UL), () => _ufle12jhs77_nameTextId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_descTextId;
		public static BansheeGz.BGDatabase.BGFieldString _descTextId => _ufle12jhs77_descTextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5037343836618115989UL, 10984033664034706347UL), () => _ufle12jhs77_descTextId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_imageId;
		public static BansheeGz.BGDatabase.BGFieldString _imageId => _ufle12jhs77_imageId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5200284452522658981UL, 456466506146157477UL), () => _ufle12jhs77_imageId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_rarity;
		public static BansheeGz.BGDatabase.BGFieldString _rarity => _ufle12jhs77_rarity ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5420841983267957128UL, 13673821402396557722UL), () => _ufle12jhs77_rarity = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillId;
		public static BansheeGz.BGDatabase.BGFieldString _skillId => _ufle12jhs77_skillId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4723893209159479566UL, 14558590460380034194UL), () => _ufle12jhs77_skillId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_itemCategory;
		public static BansheeGz.BGDatabase.BGFieldString _itemCategory => _ufle12jhs77_itemCategory ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4685351210643547513UL, 13399976397344204697UL), () => _ufle12jhs77_itemCategory = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_itemKey;
		public static BansheeGz.BGDatabase.BGKey _itemKey => _edeht3sdad33_itemKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5143607304848527015UL, 7365993704547434146UL), () => _edeht3sdad33_itemKey = null);
		private item() : base(MetaDefault) {}
		private item(BGId id) : base(MetaDefault, id) {}
		private item(BGMetaEntity meta) : base(meta) {}
		private item(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static item FindEntity(Predicate<item> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<item> FindEntities(Predicate<item> filter, List<item> result=null, Comparison<item> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<item> action, Predicate<item> filter=null, Comparison<item> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static item GetEntity(BGId entityId) => (item) MetaDefault.GetEntity(entityId);
		public static item GetEntity(int index) => (item) MetaDefault[index];
		public static item GetEntity(string entityName) => (item) MetaDefault.GetEntity(entityName);
		public static item NewEntity() => (item) MetaDefault.NewEntity();
		public static item NewEntity(BGId entityId) => (item) MetaDefault.NewEntity(entityId);
		public static item NewEntity(Action<item> callback) => (item) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((item)entity)));
		public static item GetEntityByKeyitemKey(System.String itemId) => (item) _itemKey.GetEntityByKey<System.String>(itemId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5062203024016324111UL,13564969964457416608UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5021313763942901040UL, 3028225332249866880UL));
			_ufle12jhs77_itemId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5711455164051416651UL, 1298899124958642566UL));
			_ufle12jhs77_nameTextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4729552418832784748UL, 8956478432743926673UL));
			_ufle12jhs77_descTextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5037343836618115989UL, 10984033664034706347UL));
			_ufle12jhs77_imageId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5200284452522658981UL, 456466506146157477UL));
			_ufle12jhs77_rarity = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5420841983267957128UL, 13673821402396557722UL));
			_ufle12jhs77_skillId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4723893209159479566UL, 14558590460380034194UL));
			_ufle12jhs77_itemCategory = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4685351210643547513UL, 13399976397344204697UL));
			_edeht3sdad33_itemKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5143607304848527015UL, 7365993704547434146UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_itemId = null;
			_ufle12jhs77_nameTextId = null;
			_ufle12jhs77_descTextId = null;
			_ufle12jhs77_imageId = null;
			_ufle12jhs77_rarity = null;
			_ufle12jhs77_skillId = null;
			_ufle12jhs77_itemCategory = null;
			_edeht3sdad33_itemKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new item(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new item(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "item";
			public const string name = "name";
			public const string itemId = "itemId";
			public const string nameTextId = "nameTextId";
			public const string descTextId = "descTextId";
			public const string imageId = "imageId";
			public const string rarity = "rarity";
			public const string skillId = "skillId";
			public const string itemCategory = "itemCategory";
			public const string itemKey = "itemKey";
		}
	}
}
#pragma warning restore 414
