using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class jankenCompatibility : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4719415438810398526UL,16877316380046874528UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String jankenId
		{
			get => _jankenId[Index];
			set => _jankenId[Index] = value;
		}
		public System.Int32 jan_Rock
		{
			get => _jan_Rock[Index];
			set => _jan_Rock.SetValue(this, value);
		}
		public System.Int32 jan_Paper
		{
			get => _jan_Paper[Index];
			set => _jan_Paper.SetValue(this, value);
		}
		public System.Int32 jan_Scissors
		{
			get => _jan_Scissors[Index];
			set => _jan_Scissors.SetValue(this, value);
		}
		public System.Int32 jan_Infinity
		{
			get => _jan_Infinity[Index];
			set => _jan_Infinity.SetValue(this, value);
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4684166708220110806UL, 17549061292031262087UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_jankenId;
		public static BansheeGz.BGDatabase.BGFieldString _jankenId => _ufle12jhs77_jankenId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4881314106853475830UL, 14873828172957228975UL), () => _ufle12jhs77_jankenId = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_jan_Rock;
		public static BansheeGz.BGDatabase.BGFieldInt _jan_Rock => _ufle12jhs77_jan_Rock ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5627448458937827204UL, 8329877114180163230UL), () => _ufle12jhs77_jan_Rock = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_jan_Paper;
		public static BansheeGz.BGDatabase.BGFieldInt _jan_Paper => _ufle12jhs77_jan_Paper ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5174489615615893602UL, 10749773736774372236UL), () => _ufle12jhs77_jan_Paper = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_jan_Scissors;
		public static BansheeGz.BGDatabase.BGFieldInt _jan_Scissors => _ufle12jhs77_jan_Scissors ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5251245897599518522UL, 4231210390814216350UL), () => _ufle12jhs77_jan_Scissors = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_jan_Infinity;
		public static BansheeGz.BGDatabase.BGFieldInt _jan_Infinity => _ufle12jhs77_jan_Infinity ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4963104860022473920UL, 6126935139364913339UL), () => _ufle12jhs77_jan_Infinity = null);
		private jankenCompatibility() : base(MetaDefault) {}
		private jankenCompatibility(BGId id) : base(MetaDefault, id) {}
		private jankenCompatibility(BGMetaEntity meta) : base(meta) {}
		private jankenCompatibility(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static jankenCompatibility FindEntity(Predicate<jankenCompatibility> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<jankenCompatibility> FindEntities(Predicate<jankenCompatibility> filter, List<jankenCompatibility> result=null, Comparison<jankenCompatibility> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<jankenCompatibility> action, Predicate<jankenCompatibility> filter=null, Comparison<jankenCompatibility> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static jankenCompatibility GetEntity(BGId entityId) => (jankenCompatibility) MetaDefault.GetEntity(entityId);
		public static jankenCompatibility GetEntity(int index) => (jankenCompatibility) MetaDefault[index];
		public static jankenCompatibility GetEntity(string entityName) => (jankenCompatibility) MetaDefault.GetEntity(entityName);
		public static jankenCompatibility NewEntity() => (jankenCompatibility) MetaDefault.NewEntity();
		public static jankenCompatibility NewEntity(BGId entityId) => (jankenCompatibility) MetaDefault.NewEntity(entityId);
		public static jankenCompatibility NewEntity(Action<jankenCompatibility> callback) => (jankenCompatibility) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((jankenCompatibility)entity)));
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4719415438810398526UL,16877316380046874528UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4684166708220110806UL, 17549061292031262087UL));
			_ufle12jhs77_jankenId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4881314106853475830UL, 14873828172957228975UL));
			_ufle12jhs77_jan_Rock = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5627448458937827204UL, 8329877114180163230UL));
			_ufle12jhs77_jan_Paper = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5174489615615893602UL, 10749773736774372236UL));
			_ufle12jhs77_jan_Scissors = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5251245897599518522UL, 4231210390814216350UL));
			_ufle12jhs77_jan_Infinity = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4963104860022473920UL, 6126935139364913339UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_jankenId = null;
			_ufle12jhs77_jan_Rock = null;
			_ufle12jhs77_jan_Paper = null;
			_ufle12jhs77_jan_Scissors = null;
			_ufle12jhs77_jan_Infinity = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new jankenCompatibility(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new jankenCompatibility(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "jankenCompatibility";
			public const string name = "name";
			public const string jankenId = "jankenId";
			public const string jan_Rock = "jan_Rock";
			public const string jan_Paper = "jan_Paper";
			public const string jan_Scissors = "jan_Scissors";
			public const string jan_Infinity = "jan_Infinity";
		}
	}
}
#pragma warning restore 414
