using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class janken : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5571421146950483250UL,4719544671998526385UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String jankenId
		{
			get => _jankenId[Index];
			set => _jankenId[Index] = value;
		}
		public System.String resourceId
		{
			get => _resourceId[Index];
			set => _resourceId[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5665550687258597166UL, 6529855167561385391UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_jankenId;
		public static BansheeGz.BGDatabase.BGFieldString _jankenId => _ufle12jhs77_jankenId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5599729993875994831UL, 14932085452044104845UL), () => _ufle12jhs77_jankenId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_resourceId;
		public static BansheeGz.BGDatabase.BGFieldString _resourceId => _ufle12jhs77_resourceId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5043898762345761274UL, 3981162291070891158UL), () => _ufle12jhs77_resourceId = null);
		public List<Iono.MasterData.skill> RelatedskillListUsingjankenIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.skill>(Iono.MasterData.skill._jankenId, Id);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_jankenKey;
		public static BansheeGz.BGDatabase.BGKey _jankenKey => _edeht3sdad33_jankenKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(4647064713443444640UL, 16705269008640686212UL), () => _edeht3sdad33_jankenKey = null);
		private janken() : base(MetaDefault) {}
		private janken(BGId id) : base(MetaDefault, id) {}
		private janken(BGMetaEntity meta) : base(meta) {}
		private janken(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static janken FindEntity(Predicate<janken> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<janken> FindEntities(Predicate<janken> filter, List<janken> result=null, Comparison<janken> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<janken> action, Predicate<janken> filter=null, Comparison<janken> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static janken GetEntity(BGId entityId) => (janken) MetaDefault.GetEntity(entityId);
		public static janken GetEntity(int index) => (janken) MetaDefault[index];
		public static janken GetEntity(string entityName) => (janken) MetaDefault.GetEntity(entityName);
		public static janken NewEntity() => (janken) MetaDefault.NewEntity();
		public static janken NewEntity(BGId entityId) => (janken) MetaDefault.NewEntity(entityId);
		public static janken NewEntity(Action<janken> callback) => (janken) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((janken)entity)));
		public List<Iono.MasterData.skill> FillRelatedskillListUsingjankenIdRelation(List<Iono.MasterData.skill> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.skill>(Iono.MasterData.skill._jankenId, Id, result);
		public static janken GetEntityByKeyjankenKey(System.String jankenId) => (janken) _jankenKey.GetEntityByKey<System.String>(jankenId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5571421146950483250UL,4719544671998526385UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5665550687258597166UL, 6529855167561385391UL));
			_ufle12jhs77_jankenId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5599729993875994831UL, 14932085452044104845UL));
			_ufle12jhs77_resourceId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5043898762345761274UL, 3981162291070891158UL));
			_edeht3sdad33_jankenKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(4647064713443444640UL, 16705269008640686212UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_jankenId = null;
			_ufle12jhs77_resourceId = null;
			_edeht3sdad33_jankenKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new janken(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new janken(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "janken";
			public const string name = "name";
			public const string jankenId = "jankenId";
			public const string resourceId = "resourceId";
			public const string jankenKey = "jankenKey";
		}
	}
}
#pragma warning restore 414
