using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class playerunit : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4790555902238545626UL,13817290720767131295UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String unitId
		{
			get => _unitId[Index];
			set => _unitId[Index] = value;
		}
		public System.String nameTextId
		{
			get => _nameTextId[Index];
			set => _nameTextId[Index] = value;
		}
		public System.String descTextId
		{
			get => _descTextId[Index];
			set => _descTextId[Index] = value;
		}
		public System.String memo
		{
			get => _memo[Index];
			set => _memo[Index] = value;
		}
		public System.String imageId
		{
			get => _imageId[Index];
			set => _imageId[Index] = value;
		}
		public System.String rarity
		{
			get => _rarity[Index];
			set => _rarity[Index] = value;
		}
		public System.String gender
		{
			get => _gender[Index];
			set => _gender[Index] = value;
		}
		public System.Int32 skillCount
		{
			get => _skillCount[Index];
			set => _skillCount.SetValue(this, value);
		}
		public System.Int32 maxLevel
		{
			get => _maxLevel[Index];
			set => _maxLevel.SetValue(this, value);
		}
		public System.Int32 hp
		{
			get => _hp[Index];
			set => _hp.SetValue(this, value);
		}
		public System.Int32 atk
		{
			get => _atk[Index];
			set => _atk.SetValue(this, value);
		}
		public System.Int32 def
		{
			get => _def[Index];
			set => _def.SetValue(this, value);
		}
		public System.Int32 spAtk
		{
			get => _spAtk[Index];
			set => _spAtk.SetValue(this, value);
		}
		public System.Int32 spDef
		{
			get => _spDef[Index];
			set => _spDef.SetValue(this, value);
		}
		public System.Int32 spd
		{
			get => _spd[Index];
			set => _spd.SetValue(this, value);
		}
		public System.Int32 resPoison
		{
			get => _resPoison[Index];
			set => _resPoison.SetValue(this, value);
		}
		public System.Int32 resSleep
		{
			get => _resSleep[Index];
			set => _resSleep.SetValue(this, value);
		}
		public System.Int32 resParalysis
		{
			get => _resParalysis[Index];
			set => _resParalysis.SetValue(this, value);
		}
		public System.Int32 resConfusion
		{
			get => _resConfusion[Index];
			set => _resConfusion.SetValue(this, value);
		}
		public System.String tag1
		{
			get => _tag1[Index];
			set => _tag1[Index] = value;
		}
		public System.String tag2
		{
			get => _tag2[Index];
			set => _tag2[Index] = value;
		}
		public type typeId
		{
			get => (type) _typeId[Index];
			set => _typeId[Index] = value;
		}
		public skill passiveSkillId
		{
			get => (skill) _passiveSkillId[Index];
			set => _passiveSkillId[Index] = value;
		}
		public skill skillId1
		{
			get => (skill) _skillId1[Index];
			set => _skillId1[Index] = value;
		}
		public skill skillId2
		{
			get => (skill) _skillId2[Index];
			set => _skillId2[Index] = value;
		}
		public skill skillId3
		{
			get => (skill) _skillId3[Index];
			set => _skillId3[Index] = value;
		}
		public skill skillId4
		{
			get => (skill) _skillId4[Index];
			set => _skillId4[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5711987792189006244UL, 8979065725656031661UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_unitId;
		public static BansheeGz.BGDatabase.BGFieldString _unitId => _ufle12jhs77_unitId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4918782211056987815UL, 1880893014760104365UL), () => _ufle12jhs77_unitId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_nameTextId;
		public static BansheeGz.BGDatabase.BGFieldString _nameTextId => _ufle12jhs77_nameTextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5593951532832318645UL, 11062127908080213153UL), () => _ufle12jhs77_nameTextId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_descTextId;
		public static BansheeGz.BGDatabase.BGFieldString _descTextId => _ufle12jhs77_descTextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5372350378238585134UL, 2248338357260393860UL), () => _ufle12jhs77_descTextId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_memo;
		public static BansheeGz.BGDatabase.BGFieldString _memo => _ufle12jhs77_memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5370933682758499231UL, 14734487005845470887UL), () => _ufle12jhs77_memo = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_imageId;
		public static BansheeGz.BGDatabase.BGFieldString _imageId => _ufle12jhs77_imageId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5554612168297024313UL, 354845531268512702UL), () => _ufle12jhs77_imageId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_rarity;
		public static BansheeGz.BGDatabase.BGFieldString _rarity => _ufle12jhs77_rarity ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5063780358305105810UL, 13563371573703432618UL), () => _ufle12jhs77_rarity = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_gender;
		public static BansheeGz.BGDatabase.BGFieldString _gender => _ufle12jhs77_gender ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4953366469830383534UL, 8869264681256678799UL), () => _ufle12jhs77_gender = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_skillCount;
		public static BansheeGz.BGDatabase.BGFieldInt _skillCount => _ufle12jhs77_skillCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4956197478987634439UL, 6293111570342763707UL), () => _ufle12jhs77_skillCount = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_maxLevel;
		public static BansheeGz.BGDatabase.BGFieldInt _maxLevel => _ufle12jhs77_maxLevel ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5500941242680240606UL, 1420901780259743376UL), () => _ufle12jhs77_maxLevel = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
		public static BansheeGz.BGDatabase.BGFieldInt _hp => _ufle12jhs77_hp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4965034248987378402UL, 14182597692713470135UL), () => _ufle12jhs77_hp = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
		public static BansheeGz.BGDatabase.BGFieldInt _atk => _ufle12jhs77_atk ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4652554406397077276UL, 8758061061542804411UL), () => _ufle12jhs77_atk = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_def;
		public static BansheeGz.BGDatabase.BGFieldInt _def => _ufle12jhs77_def ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5046173575029250899UL, 7493084237557323400UL), () => _ufle12jhs77_def = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_spAtk;
		public static BansheeGz.BGDatabase.BGFieldInt _spAtk => _ufle12jhs77_spAtk ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5412377546211887039UL, 8001601651195613571UL), () => _ufle12jhs77_spAtk = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_spDef;
		public static BansheeGz.BGDatabase.BGFieldInt _spDef => _ufle12jhs77_spDef ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5491746297141224202UL, 3484399786325678262UL), () => _ufle12jhs77_spDef = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_spd;
		public static BansheeGz.BGDatabase.BGFieldInt _spd => _ufle12jhs77_spd ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4948951821366855625UL, 16584289328414371477UL), () => _ufle12jhs77_spd = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_resPoison;
		public static BansheeGz.BGDatabase.BGFieldInt _resPoison => _ufle12jhs77_resPoison ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4976609343674424147UL, 5888017482204608899UL), () => _ufle12jhs77_resPoison = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_resSleep;
		public static BansheeGz.BGDatabase.BGFieldInt _resSleep => _ufle12jhs77_resSleep ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5550041623697640634UL, 14873223540570236850UL), () => _ufle12jhs77_resSleep = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_resParalysis;
		public static BansheeGz.BGDatabase.BGFieldInt _resParalysis => _ufle12jhs77_resParalysis ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5456081441574276763UL, 5910623211890558359UL), () => _ufle12jhs77_resParalysis = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_resConfusion;
		public static BansheeGz.BGDatabase.BGFieldInt _resConfusion => _ufle12jhs77_resConfusion ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4808274001478605073UL, 7873230605581973130UL), () => _ufle12jhs77_resConfusion = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_tag1;
		public static BansheeGz.BGDatabase.BGFieldString _tag1 => _ufle12jhs77_tag1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5747392093184680619UL, 11461701534163657639UL), () => _ufle12jhs77_tag1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_tag2;
		public static BansheeGz.BGDatabase.BGFieldString _tag2 => _ufle12jhs77_tag2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4990019138333856925UL, 2736679447966676656UL), () => _ufle12jhs77_tag2 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_typeId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _typeId => _ufle12jhs77_typeId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4963627942695374743UL, 12738715794954114488UL), () => _ufle12jhs77_typeId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_passiveSkillId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _passiveSkillId => _ufle12jhs77_passiveSkillId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4806765857270863595UL, 13206008134614523798UL), () => _ufle12jhs77_passiveSkillId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_skillId1;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _skillId1 => _ufle12jhs77_skillId1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5548043486257905475UL, 4037961129963009678UL), () => _ufle12jhs77_skillId1 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_skillId2;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _skillId2 => _ufle12jhs77_skillId2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4996592635650074090UL, 13245665014245800090UL), () => _ufle12jhs77_skillId2 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_skillId3;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _skillId3 => _ufle12jhs77_skillId3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4949759711241731939UL, 14486893760808706982UL), () => _ufle12jhs77_skillId3 = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_skillId4;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _skillId4 => _ufle12jhs77_skillId4 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5024013118483237566UL, 5797983135087938214UL), () => _ufle12jhs77_skillId4 = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_unitKey;
		public static BansheeGz.BGDatabase.BGKey _unitKey => _edeht3sdad33_unitKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(4917211555327134970UL, 1585179892647103120UL), () => _edeht3sdad33_unitKey = null);
		private playerunit() : base(MetaDefault) {}
		private playerunit(BGId id) : base(MetaDefault, id) {}
		private playerunit(BGMetaEntity meta) : base(meta) {}
		private playerunit(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static playerunit FindEntity(Predicate<playerunit> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<playerunit> FindEntities(Predicate<playerunit> filter, List<playerunit> result=null, Comparison<playerunit> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<playerunit> action, Predicate<playerunit> filter=null, Comparison<playerunit> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static playerunit GetEntity(BGId entityId) => (playerunit) MetaDefault.GetEntity(entityId);
		public static playerunit GetEntity(int index) => (playerunit) MetaDefault[index];
		public static playerunit GetEntity(string entityName) => (playerunit) MetaDefault.GetEntity(entityName);
		public static playerunit NewEntity() => (playerunit) MetaDefault.NewEntity();
		public static playerunit NewEntity(BGId entityId) => (playerunit) MetaDefault.NewEntity(entityId);
		public static playerunit NewEntity(Action<playerunit> callback) => (playerunit) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((playerunit)entity)));
		public static playerunit GetEntityByKeyunitKey(System.String unitId) => (playerunit) _unitKey.GetEntityByKey<System.String>(unitId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4790555902238545626UL,13817290720767131295UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5711987792189006244UL, 8979065725656031661UL));
			_ufle12jhs77_unitId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4918782211056987815UL, 1880893014760104365UL));
			_ufle12jhs77_nameTextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5593951532832318645UL, 11062127908080213153UL));
			_ufle12jhs77_descTextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5372350378238585134UL, 2248338357260393860UL));
			_ufle12jhs77_memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5370933682758499231UL, 14734487005845470887UL));
			_ufle12jhs77_imageId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5554612168297024313UL, 354845531268512702UL));
			_ufle12jhs77_rarity = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5063780358305105810UL, 13563371573703432618UL));
			_ufle12jhs77_gender = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4953366469830383534UL, 8869264681256678799UL));
			_ufle12jhs77_skillCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4956197478987634439UL, 6293111570342763707UL));
			_ufle12jhs77_maxLevel = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5500941242680240606UL, 1420901780259743376UL));
			_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4965034248987378402UL, 14182597692713470135UL));
			_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4652554406397077276UL, 8758061061542804411UL));
			_ufle12jhs77_def = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5046173575029250899UL, 7493084237557323400UL));
			_ufle12jhs77_spAtk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5412377546211887039UL, 8001601651195613571UL));
			_ufle12jhs77_spDef = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5491746297141224202UL, 3484399786325678262UL));
			_ufle12jhs77_spd = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4948951821366855625UL, 16584289328414371477UL));
			_ufle12jhs77_resPoison = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4976609343674424147UL, 5888017482204608899UL));
			_ufle12jhs77_resSleep = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5550041623697640634UL, 14873223540570236850UL));
			_ufle12jhs77_resParalysis = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5456081441574276763UL, 5910623211890558359UL));
			_ufle12jhs77_resConfusion = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4808274001478605073UL, 7873230605581973130UL));
			_ufle12jhs77_tag1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5747392093184680619UL, 11461701534163657639UL));
			_ufle12jhs77_tag2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4990019138333856925UL, 2736679447966676656UL));
			_ufle12jhs77_typeId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4963627942695374743UL, 12738715794954114488UL));
			_ufle12jhs77_passiveSkillId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4806765857270863595UL, 13206008134614523798UL));
			_ufle12jhs77_skillId1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5548043486257905475UL, 4037961129963009678UL));
			_ufle12jhs77_skillId2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4996592635650074090UL, 13245665014245800090UL));
			_ufle12jhs77_skillId3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4949759711241731939UL, 14486893760808706982UL));
			_ufle12jhs77_skillId4 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5024013118483237566UL, 5797983135087938214UL));
			_edeht3sdad33_unitKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(4917211555327134970UL, 1585179892647103120UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_unitId = null;
			_ufle12jhs77_nameTextId = null;
			_ufle12jhs77_descTextId = null;
			_ufle12jhs77_memo = null;
			_ufle12jhs77_imageId = null;
			_ufle12jhs77_rarity = null;
			_ufle12jhs77_gender = null;
			_ufle12jhs77_skillCount = null;
			_ufle12jhs77_maxLevel = null;
			_ufle12jhs77_hp = null;
			_ufle12jhs77_atk = null;
			_ufle12jhs77_def = null;
			_ufle12jhs77_spAtk = null;
			_ufle12jhs77_spDef = null;
			_ufle12jhs77_spd = null;
			_ufle12jhs77_resPoison = null;
			_ufle12jhs77_resSleep = null;
			_ufle12jhs77_resParalysis = null;
			_ufle12jhs77_resConfusion = null;
			_ufle12jhs77_tag1 = null;
			_ufle12jhs77_tag2 = null;
			_ufle12jhs77_typeId = null;
			_ufle12jhs77_passiveSkillId = null;
			_ufle12jhs77_skillId1 = null;
			_ufle12jhs77_skillId2 = null;
			_ufle12jhs77_skillId3 = null;
			_ufle12jhs77_skillId4 = null;
			_edeht3sdad33_unitKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new playerunit(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new playerunit(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "playerunit";
			public const string name = "name";
			public const string unitId = "unitId";
			public const string nameTextId = "nameTextId";
			public const string descTextId = "descTextId";
			public const string memo = "memo";
			public const string imageId = "imageId";
			public const string rarity = "rarity";
			public const string gender = "gender";
			public const string skillCount = "skillCount";
			public const string maxLevel = "maxLevel";
			public const string hp = "hp";
			public const string atk = "atk";
			public const string def = "def";
			public const string spAtk = "spAtk";
			public const string spDef = "spDef";
			public const string spd = "spd";
			public const string resPoison = "resPoison";
			public const string resSleep = "resSleep";
			public const string resParalysis = "resParalysis";
			public const string resConfusion = "resConfusion";
			public const string tag1 = "tag1";
			public const string tag2 = "tag2";
			public const string typeId = "typeId";
			public const string passiveSkillId = "passiveSkillId";
			public const string skillId1 = "skillId1";
			public const string skillId2 = "skillId2";
			public const string skillId3 = "skillId3";
			public const string skillId4 = "skillId4";
			public const string unitKey = "unitKey";
		}
	}
}
#pragma warning restore 414
