using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class skill : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4991386664094160810UL,17110501976578085561UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String skillId
		{
			get => _skillId[Index];
			set => _skillId[Index] = value;
		}
		public System.String nameTextId
		{
			get => _nameTextId[Index];
			set => _nameTextId[Index] = value;
		}
		public System.String descTextId
		{
			get => _descTextId[Index];
			set => _descTextId[Index] = value;
		}
		public System.String memo
		{
			get => _memo[Index];
			set => _memo[Index] = value;
		}
		public System.String effectName
		{
			get => _effectName[Index];
			set => _effectName[Index] = value;
		}
		public System.String hpCostType
		{
			get => _hpCostType[Index];
			set => _hpCostType[Index] = value;
		}
		public System.Int32 hpCostRate
		{
			get => _hpCostRate[Index];
			set => _hpCostRate.SetValue(this, value);
		}
		public System.String targetRange
		{
			get => _targetRange[Index];
			set => _targetRange[Index] = value;
		}
		public System.String skillCategory
		{
			get => _skillCategory[Index];
			set => _skillCategory[Index] = value;
		}
		public System.String activationTiming
		{
			get => _activationTiming[Index];
			set => _activationTiming[Index] = value;
		}
		public System.String effectTarget
		{
			get => _effectTarget[Index];
			set => _effectTarget[Index] = value;
		}
		public System.String effectType
		{
			get => _effectType[Index];
			set => _effectType[Index] = value;
		}
		public System.String physicMagicType
		{
			get => _physicMagicType[Index];
			set => _physicMagicType[Index] = value;
		}
		public System.Int32 power
		{
			get => _power[Index];
			set => _power.SetValue(this, value);
		}
		public System.Int32 accuracy
		{
			get => _accuracy[Index];
			set => _accuracy.SetValue(this, value);
		}
		public System.Int32 hpDrainRate
		{
			get => _hpDrainRate[Index];
			set => _hpDrainRate.SetValue(this, value);
		}
		public System.Int32 powerAtMaxHp
		{
			get => _powerAtMaxHp[Index];
			set => _powerAtMaxHp.SetValue(this, value);
		}
		public System.Int32 powerAtMinHp
		{
			get => _powerAtMinHp[Index];
			set => _powerAtMinHp.SetValue(this, value);
		}
		public System.String applyBuffBeforeAttack
		{
			get => _applyBuffBeforeAttack[Index];
			set => _applyBuffBeforeAttack[Index] = value;
		}
		public System.Int32 barrierCount
		{
			get => _barrierCount[Index];
			set => _barrierCount.SetValue(this, value);
		}
		public System.String barrierType
		{
			get => _barrierType[Index];
			set => _barrierType[Index] = value;
		}
		public System.Int32 barrierMaxStacks
		{
			get => _barrierMaxStacks[Index];
			set => _barrierMaxStacks.SetValue(this, value);
		}
		public System.Int32 barrierTurnCount
		{
			get => _barrierTurnCount[Index];
			set => _barrierTurnCount.SetValue(this, value);
		}
		public System.String barrierConsumeTiming
		{
			get => _barrierConsumeTiming[Index];
			set => _barrierConsumeTiming[Index] = value;
		}
		public System.Int32 shieldCount
		{
			get => _shieldCount[Index];
			set => _shieldCount.SetValue(this, value);
		}
		public System.Int32 shieldReduceRate
		{
			get => _shieldReduceRate[Index];
			set => _shieldReduceRate.SetValue(this, value);
		}
		public System.Int32 shieldReduceValue
		{
			get => _shieldReduceValue[Index];
			set => _shieldReduceValue.SetValue(this, value);
		}
		public System.String shieldType
		{
			get => _shieldType[Index];
			set => _shieldType[Index] = value;
		}
		public System.Int32 shieldTurnCount
		{
			get => _shieldTurnCount[Index];
			set => _shieldTurnCount.SetValue(this, value);
		}
		public System.String shieldConsumeTiming
		{
			get => _shieldConsumeTiming[Index];
			set => _shieldConsumeTiming[Index] = value;
		}
		public System.Int32 minHitCount
		{
			get => _minHitCount[Index];
			set => _minHitCount.SetValue(this, value);
		}
		public System.Int32 maxHitCount
		{
			get => _maxHitCount[Index];
			set => _maxHitCount.SetValue(this, value);
		}
		public System.Int32 multiHitProbability
		{
			get => _multiHitProbability[Index];
			set => _multiHitProbability.SetValue(this, value);
		}
		public System.Int32 criticalRank
		{
			get => _criticalRank[Index];
			set => _criticalRank.SetValue(this, value);
		}
		public System.Int32 fixedDamageValue
		{
			get => _fixedDamageValue[Index];
			set => _fixedDamageValue.SetValue(this, value);
		}
		public System.String weatherId
		{
			get => _weatherId[Index];
			set => _weatherId[Index] = value;
		}
		public System.String fieldId
		{
			get => _fieldId[Index];
			set => _fieldId[Index] = value;
		}
		public System.String specialEffectConditionId
		{
			get => _specialEffectConditionId[Index];
			set => _specialEffectConditionId[Index] = value;
		}
		public System.Int32 actionPriority
		{
			get => _actionPriority[Index];
			set => _actionPriority.SetValue(this, value);
		}
		public janken jankenId
		{
			get => (janken) _jankenId[Index];
			set => _jankenId[Index] = value;
		}
		public buffdebuff targetBuffId
		{
			get => (buffdebuff) _targetBuffId[Index];
			set => _targetBuffId[Index] = value;
		}
		public buffdebuff userBuffId
		{
			get => (buffdebuff) _userBuffId[Index];
			set => _userBuffId[Index] = value;
		}
		public abnormalcondition targetConditionId
		{
			get => (abnormalcondition) _targetConditionId[Index];
			set => _targetConditionId[Index] = value;
		}
		public abnormalcondition userConditionId
		{
			get => (abnormalcondition) _userConditionId[Index];
			set => _userConditionId[Index] = value;
		}
		public System.Boolean guaranteedHitFlag
		{
			get => _guaranteedHitFlag[Index];
			set => _guaranteedHitFlag.SetValue(this, value);
		}
		public System.Boolean pierceBarrierFlag
		{
			get => _pierceBarrierFlag[Index];
			set => _pierceBarrierFlag.SetValue(this, value);
		}
		public System.Boolean pierceShieldFlag
		{
			get => _pierceShieldFlag[Index];
			set => _pierceShieldFlag.SetValue(this, value);
		}
		public System.Boolean changeWeatherFlag
		{
			get => _changeWeatherFlag[Index];
			set => _changeWeatherFlag.SetValue(this, value);
		}
		public System.Boolean changeFieldFlag
		{
			get => _changeFieldFlag[Index];
			set => _changeFieldFlag.SetValue(this, value);
		}
		public System.Boolean fixedDamageFlag
		{
			get => _fixedDamageFlag[Index];
			set => _fixedDamageFlag.SetValue(this, value);
		}
		public System.Boolean selfDestructFlag
		{
			get => _selfDestructFlag[Index];
			set => _selfDestructFlag.SetValue(this, value);
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5123197815993307180UL, 8952811171006590352UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillId;
		public static BansheeGz.BGDatabase.BGFieldString _skillId => _ufle12jhs77_skillId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5564587523474765270UL, 1294950214858330262UL), () => _ufle12jhs77_skillId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_nameTextId;
		public static BansheeGz.BGDatabase.BGFieldString _nameTextId => _ufle12jhs77_nameTextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5028464223891344734UL, 8566364085774726528UL), () => _ufle12jhs77_nameTextId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_descTextId;
		public static BansheeGz.BGDatabase.BGFieldString _descTextId => _ufle12jhs77_descTextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5439663439260675812UL, 10476946944847286972UL), () => _ufle12jhs77_descTextId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_memo;
		public static BansheeGz.BGDatabase.BGFieldString _memo => _ufle12jhs77_memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5061852327322488097UL, 16199365995649067178UL), () => _ufle12jhs77_memo = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_effectName;
		public static BansheeGz.BGDatabase.BGFieldString _effectName => _ufle12jhs77_effectName ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4628221513896147583UL, 12220060615704579209UL), () => _ufle12jhs77_effectName = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_hpCostType;
		public static BansheeGz.BGDatabase.BGFieldString _hpCostType => _ufle12jhs77_hpCostType ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4773813737000342953UL, 1124626644191571368UL), () => _ufle12jhs77_hpCostType = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hpCostRate;
		public static BansheeGz.BGDatabase.BGFieldInt _hpCostRate => _ufle12jhs77_hpCostRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5227891913592704615UL, 10682445581066460062UL), () => _ufle12jhs77_hpCostRate = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_targetRange;
		public static BansheeGz.BGDatabase.BGFieldString _targetRange => _ufle12jhs77_targetRange ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5412589636230779234UL, 7931870133307920015UL), () => _ufle12jhs77_targetRange = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillCategory;
		public static BansheeGz.BGDatabase.BGFieldString _skillCategory => _ufle12jhs77_skillCategory ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5576513928377552706UL, 16286577180931151024UL), () => _ufle12jhs77_skillCategory = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_activationTiming;
		public static BansheeGz.BGDatabase.BGFieldString _activationTiming => _ufle12jhs77_activationTiming ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5762200464347231997UL, 1117368868151638922UL), () => _ufle12jhs77_activationTiming = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_effectTarget;
		public static BansheeGz.BGDatabase.BGFieldString _effectTarget => _ufle12jhs77_effectTarget ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4646532030078909059UL, 7434181656346080689UL), () => _ufle12jhs77_effectTarget = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_effectType;
		public static BansheeGz.BGDatabase.BGFieldString _effectType => _ufle12jhs77_effectType ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4720836788560143424UL, 929558016611191468UL), () => _ufle12jhs77_effectType = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_physicMagicType;
		public static BansheeGz.BGDatabase.BGFieldString _physicMagicType => _ufle12jhs77_physicMagicType ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4641536565812489476UL, 5376925982990865562UL), () => _ufle12jhs77_physicMagicType = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_power;
		public static BansheeGz.BGDatabase.BGFieldInt _power => _ufle12jhs77_power ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4637042118216186344UL, 12574305154716340107UL), () => _ufle12jhs77_power = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_accuracy;
		public static BansheeGz.BGDatabase.BGFieldInt _accuracy => _ufle12jhs77_accuracy ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5737700373714774179UL, 8776513802547622806UL), () => _ufle12jhs77_accuracy = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hpDrainRate;
		public static BansheeGz.BGDatabase.BGFieldInt _hpDrainRate => _ufle12jhs77_hpDrainRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5110078382729692860UL, 6264513899783822256UL), () => _ufle12jhs77_hpDrainRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_powerAtMaxHp;
		public static BansheeGz.BGDatabase.BGFieldInt _powerAtMaxHp => _ufle12jhs77_powerAtMaxHp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4613477944408570408UL, 4354403803415210383UL), () => _ufle12jhs77_powerAtMaxHp = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_powerAtMinHp;
		public static BansheeGz.BGDatabase.BGFieldInt _powerAtMinHp => _ufle12jhs77_powerAtMinHp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5267833106342808989UL, 9330195630183223478UL), () => _ufle12jhs77_powerAtMinHp = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_applyBuffBeforeAttack;
		public static BansheeGz.BGDatabase.BGFieldString _applyBuffBeforeAttack => _ufle12jhs77_applyBuffBeforeAttack ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5592700155671556089UL, 14562699680275663761UL), () => _ufle12jhs77_applyBuffBeforeAttack = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_barrierCount;
		public static BansheeGz.BGDatabase.BGFieldInt _barrierCount => _ufle12jhs77_barrierCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4905594079219648901UL, 4782333500667968169UL), () => _ufle12jhs77_barrierCount = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_barrierType;
		public static BansheeGz.BGDatabase.BGFieldString _barrierType => _ufle12jhs77_barrierType ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4740267406708086830UL, 4860818211560625840UL), () => _ufle12jhs77_barrierType = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_barrierMaxStacks;
		public static BansheeGz.BGDatabase.BGFieldInt _barrierMaxStacks => _ufle12jhs77_barrierMaxStacks ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5250558137787005958UL, 9748678008777579950UL), () => _ufle12jhs77_barrierMaxStacks = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_barrierTurnCount;
		public static BansheeGz.BGDatabase.BGFieldInt _barrierTurnCount => _ufle12jhs77_barrierTurnCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4612954344996954971UL, 14532113558383121285UL), () => _ufle12jhs77_barrierTurnCount = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_barrierConsumeTiming;
		public static BansheeGz.BGDatabase.BGFieldString _barrierConsumeTiming => _ufle12jhs77_barrierConsumeTiming ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4823999288065018093UL, 237384997565385872UL), () => _ufle12jhs77_barrierConsumeTiming = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_shieldCount;
		public static BansheeGz.BGDatabase.BGFieldInt _shieldCount => _ufle12jhs77_shieldCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5557474931146725949UL, 1127640947207694736UL), () => _ufle12jhs77_shieldCount = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_shieldReduceRate;
		public static BansheeGz.BGDatabase.BGFieldInt _shieldReduceRate => _ufle12jhs77_shieldReduceRate ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5058332562245703565UL, 159253669131743419UL), () => _ufle12jhs77_shieldReduceRate = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_shieldReduceValue;
		public static BansheeGz.BGDatabase.BGFieldInt _shieldReduceValue => _ufle12jhs77_shieldReduceValue ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4929955633929737773UL, 6685302594716022457UL), () => _ufle12jhs77_shieldReduceValue = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_shieldType;
		public static BansheeGz.BGDatabase.BGFieldString _shieldType => _ufle12jhs77_shieldType ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5093747158784167573UL, 1956505319053047977UL), () => _ufle12jhs77_shieldType = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_shieldTurnCount;
		public static BansheeGz.BGDatabase.BGFieldInt _shieldTurnCount => _ufle12jhs77_shieldTurnCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5078430129893868918UL, 3597230572675272065UL), () => _ufle12jhs77_shieldTurnCount = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_shieldConsumeTiming;
		public static BansheeGz.BGDatabase.BGFieldString _shieldConsumeTiming => _ufle12jhs77_shieldConsumeTiming ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5292969565786891537UL, 1983263918192796606UL), () => _ufle12jhs77_shieldConsumeTiming = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_minHitCount;
		public static BansheeGz.BGDatabase.BGFieldInt _minHitCount => _ufle12jhs77_minHitCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5436368627586532650UL, 14896207939897029814UL), () => _ufle12jhs77_minHitCount = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_maxHitCount;
		public static BansheeGz.BGDatabase.BGFieldInt _maxHitCount => _ufle12jhs77_maxHitCount ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5030497505215193602UL, 13664124320077053591UL), () => _ufle12jhs77_maxHitCount = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_multiHitProbability;
		public static BansheeGz.BGDatabase.BGFieldInt _multiHitProbability => _ufle12jhs77_multiHitProbability ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4805475120714811248UL, 15581915683448628159UL), () => _ufle12jhs77_multiHitProbability = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_criticalRank;
		public static BansheeGz.BGDatabase.BGFieldInt _criticalRank => _ufle12jhs77_criticalRank ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4723589441987687754UL, 14396295602532719493UL), () => _ufle12jhs77_criticalRank = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_fixedDamageValue;
		public static BansheeGz.BGDatabase.BGFieldInt _fixedDamageValue => _ufle12jhs77_fixedDamageValue ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5648380328627578546UL, 13521494063829986460UL), () => _ufle12jhs77_fixedDamageValue = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_weatherId;
		public static BansheeGz.BGDatabase.BGFieldString _weatherId => _ufle12jhs77_weatherId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5662601799301234738UL, 11264563223222987924UL), () => _ufle12jhs77_weatherId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_fieldId;
		public static BansheeGz.BGDatabase.BGFieldString _fieldId => _ufle12jhs77_fieldId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5612673836658491151UL, 1641981486371500708UL), () => _ufle12jhs77_fieldId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_specialEffectConditionId;
		public static BansheeGz.BGDatabase.BGFieldString _specialEffectConditionId => _ufle12jhs77_specialEffectConditionId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5520366845888038246UL, 479922739760700577UL), () => _ufle12jhs77_specialEffectConditionId = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_actionPriority;
		public static BansheeGz.BGDatabase.BGFieldInt _actionPriority => _ufle12jhs77_actionPriority ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5585228350396183635UL, 1755979379901214120UL), () => _ufle12jhs77_actionPriority = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_jankenId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _jankenId => _ufle12jhs77_jankenId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5296176783062435024UL, 17158704863935787938UL), () => _ufle12jhs77_jankenId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_targetBuffId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _targetBuffId => _ufle12jhs77_targetBuffId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5621538147706099530UL, 15640345406603901104UL), () => _ufle12jhs77_targetBuffId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_userBuffId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _userBuffId => _ufle12jhs77_userBuffId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4902629646387887520UL, 10390537468717415060UL), () => _ufle12jhs77_userBuffId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_targetConditionId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _targetConditionId => _ufle12jhs77_targetConditionId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5560822096214341257UL, 13891741393878146481UL), () => _ufle12jhs77_targetConditionId = null);
		private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_userConditionId;
		public static BansheeGz.BGDatabase.BGFieldRelationSingle _userConditionId => _ufle12jhs77_userConditionId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4635459305867907458UL, 4959464754983229357UL), () => _ufle12jhs77_userConditionId = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_guaranteedHitFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _guaranteedHitFlag => _ufle12jhs77_guaranteedHitFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5086269220495800226UL, 6394174357496699269UL), () => _ufle12jhs77_guaranteedHitFlag = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_pierceBarrierFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _pierceBarrierFlag => _ufle12jhs77_pierceBarrierFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(4616835570647001322UL, 3697461208925056143UL), () => _ufle12jhs77_pierceBarrierFlag = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_pierceShieldFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _pierceShieldFlag => _ufle12jhs77_pierceShieldFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5564772478280759691UL, 16934115719918024364UL), () => _ufle12jhs77_pierceShieldFlag = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_changeWeatherFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _changeWeatherFlag => _ufle12jhs77_changeWeatherFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5614678605245773606UL, 17296149091790613183UL), () => _ufle12jhs77_changeWeatherFlag = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_changeFieldFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _changeFieldFlag => _ufle12jhs77_changeFieldFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5525816365690520623UL, 8949687732978284214UL), () => _ufle12jhs77_changeFieldFlag = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_fixedDamageFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _fixedDamageFlag => _ufle12jhs77_fixedDamageFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5307445969301647497UL, 14746900741543460512UL), () => _ufle12jhs77_fixedDamageFlag = null);
		private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_selfDestructFlag;
		public static BansheeGz.BGDatabase.BGFieldBool _selfDestructFlag => _ufle12jhs77_selfDestructFlag ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(4625049298063639268UL, 4654949951376471970UL), () => _ufle12jhs77_selfDestructFlag = null);
		public List<Iono.MasterData.playerunit> RelatedplayerunitListUsingpassiveSkillIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._passiveSkillId, Id);
		public List<Iono.MasterData.playerunit> RelatedplayerunitListUsingskillId1Relation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._skillId1, Id);
		public List<Iono.MasterData.playerunit> RelatedplayerunitListUsingskillId2Relation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._skillId2, Id);
		public List<Iono.MasterData.playerunit> RelatedplayerunitListUsingskillId3Relation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._skillId3, Id);
		public List<Iono.MasterData.playerunit> RelatedplayerunitListUsingskillId4Relation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._skillId4, Id);
		public List<Iono.MasterData.enemyunit> RelatedenemyunitListUsingpassiveSkillIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyunit>(Iono.MasterData.enemyunit._passiveSkillId, Id);
		public List<Iono.MasterData.enemyslotdetail> RelatedenemyslotdetailListUsingskillIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyslotdetail>(Iono.MasterData.enemyslotdetail._skillId, Id);
		public List<Iono.MasterData.item> RelateditemListUsingskillIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.item>(Iono.MasterData.item._skillId, Id);
		public List<Iono.MasterData.field> RelatedfieldListUsingnegatedSkillIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.field>(Iono.MasterData.field._negatedSkillId, Id);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_skillKey;
		public static BansheeGz.BGDatabase.BGKey _skillKey => _edeht3sdad33_skillKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5565842710707110596UL, 11905549077091789974UL), () => _edeht3sdad33_skillKey = null);
		private skill() : base(MetaDefault) {}
		private skill(BGId id) : base(MetaDefault, id) {}
		private skill(BGMetaEntity meta) : base(meta) {}
		private skill(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static skill FindEntity(Predicate<skill> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<skill> FindEntities(Predicate<skill> filter, List<skill> result=null, Comparison<skill> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<skill> action, Predicate<skill> filter=null, Comparison<skill> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static skill GetEntity(BGId entityId) => (skill) MetaDefault.GetEntity(entityId);
		public static skill GetEntity(int index) => (skill) MetaDefault[index];
		public static skill GetEntity(string entityName) => (skill) MetaDefault.GetEntity(entityName);
		public static skill NewEntity() => (skill) MetaDefault.NewEntity();
		public static skill NewEntity(BGId entityId) => (skill) MetaDefault.NewEntity(entityId);
		public static skill NewEntity(Action<skill> callback) => (skill) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((skill)entity)));
		public List<Iono.MasterData.playerunit> FillRelatedplayerunitListUsingpassiveSkillIdRelation(List<Iono.MasterData.playerunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._passiveSkillId, Id, result);
		public List<Iono.MasterData.playerunit> FillRelatedplayerunitListUsingskillId1Relation(List<Iono.MasterData.playerunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._skillId1, Id, result);
		public List<Iono.MasterData.playerunit> FillRelatedplayerunitListUsingskillId2Relation(List<Iono.MasterData.playerunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._skillId2, Id, result);
		public List<Iono.MasterData.playerunit> FillRelatedplayerunitListUsingskillId3Relation(List<Iono.MasterData.playerunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._skillId3, Id, result);
		public List<Iono.MasterData.playerunit> FillRelatedplayerunitListUsingskillId4Relation(List<Iono.MasterData.playerunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.playerunit>(Iono.MasterData.playerunit._skillId4, Id, result);
		public List<Iono.MasterData.enemyunit> FillRelatedenemyunitListUsingpassiveSkillIdRelation(List<Iono.MasterData.enemyunit> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyunit>(Iono.MasterData.enemyunit._passiveSkillId, Id, result);
		public List<Iono.MasterData.enemyslotdetail> FillRelatedenemyslotdetailListUsingskillIdRelation(List<Iono.MasterData.enemyslotdetail> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.enemyslotdetail>(Iono.MasterData.enemyslotdetail._skillId, Id, result);
		public List<Iono.MasterData.item> FillRelateditemListUsingskillIdRelation(List<Iono.MasterData.item> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.item>(Iono.MasterData.item._skillId, Id, result);
		public List<Iono.MasterData.field> FillRelatedfieldListUsingnegatedSkillIdRelation(List<Iono.MasterData.field> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.field>(Iono.MasterData.field._negatedSkillId, Id, result);
		public static skill GetEntityByKeyskillKey(System.String skillId) => (skill) _skillKey.GetEntityByKey<System.String>(skillId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4991386664094160810UL,17110501976578085561UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5123197815993307180UL, 8952811171006590352UL));
			_ufle12jhs77_skillId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5564587523474765270UL, 1294950214858330262UL));
			_ufle12jhs77_nameTextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5028464223891344734UL, 8566364085774726528UL));
			_ufle12jhs77_descTextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5439663439260675812UL, 10476946944847286972UL));
			_ufle12jhs77_memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5061852327322488097UL, 16199365995649067178UL));
			_ufle12jhs77_effectName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4628221513896147583UL, 12220060615704579209UL));
			_ufle12jhs77_hpCostType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4773813737000342953UL, 1124626644191571368UL));
			_ufle12jhs77_hpCostRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5227891913592704615UL, 10682445581066460062UL));
			_ufle12jhs77_targetRange = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5412589636230779234UL, 7931870133307920015UL));
			_ufle12jhs77_skillCategory = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5576513928377552706UL, 16286577180931151024UL));
			_ufle12jhs77_activationTiming = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5762200464347231997UL, 1117368868151638922UL));
			_ufle12jhs77_effectTarget = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4646532030078909059UL, 7434181656346080689UL));
			_ufle12jhs77_effectType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4720836788560143424UL, 929558016611191468UL));
			_ufle12jhs77_physicMagicType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4641536565812489476UL, 5376925982990865562UL));
			_ufle12jhs77_power = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4637042118216186344UL, 12574305154716340107UL));
			_ufle12jhs77_accuracy = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5737700373714774179UL, 8776513802547622806UL));
			_ufle12jhs77_hpDrainRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5110078382729692860UL, 6264513899783822256UL));
			_ufle12jhs77_powerAtMaxHp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4613477944408570408UL, 4354403803415210383UL));
			_ufle12jhs77_powerAtMinHp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5267833106342808989UL, 9330195630183223478UL));
			_ufle12jhs77_applyBuffBeforeAttack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5592700155671556089UL, 14562699680275663761UL));
			_ufle12jhs77_barrierCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4905594079219648901UL, 4782333500667968169UL));
			_ufle12jhs77_barrierType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4740267406708086830UL, 4860818211560625840UL));
			_ufle12jhs77_barrierMaxStacks = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5250558137787005958UL, 9748678008777579950UL));
			_ufle12jhs77_barrierTurnCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4612954344996954971UL, 14532113558383121285UL));
			_ufle12jhs77_barrierConsumeTiming = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4823999288065018093UL, 237384997565385872UL));
			_ufle12jhs77_shieldCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5557474931146725949UL, 1127640947207694736UL));
			_ufle12jhs77_shieldReduceRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5058332562245703565UL, 159253669131743419UL));
			_ufle12jhs77_shieldReduceValue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4929955633929737773UL, 6685302594716022457UL));
			_ufle12jhs77_shieldType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5093747158784167573UL, 1956505319053047977UL));
			_ufle12jhs77_shieldTurnCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5078430129893868918UL, 3597230572675272065UL));
			_ufle12jhs77_shieldConsumeTiming = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5292969565786891537UL, 1983263918192796606UL));
			_ufle12jhs77_minHitCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5436368627586532650UL, 14896207939897029814UL));
			_ufle12jhs77_maxHitCount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5030497505215193602UL, 13664124320077053591UL));
			_ufle12jhs77_multiHitProbability = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4805475120714811248UL, 15581915683448628159UL));
			_ufle12jhs77_criticalRank = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4723589441987687754UL, 14396295602532719493UL));
			_ufle12jhs77_fixedDamageValue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5648380328627578546UL, 13521494063829986460UL));
			_ufle12jhs77_weatherId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5662601799301234738UL, 11264563223222987924UL));
			_ufle12jhs77_fieldId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5612673836658491151UL, 1641981486371500708UL));
			_ufle12jhs77_specialEffectConditionId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5520366845888038246UL, 479922739760700577UL));
			_ufle12jhs77_actionPriority = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5585228350396183635UL, 1755979379901214120UL));
			_ufle12jhs77_jankenId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5296176783062435024UL, 17158704863935787938UL));
			_ufle12jhs77_targetBuffId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5621538147706099530UL, 15640345406603901104UL));
			_ufle12jhs77_userBuffId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4902629646387887520UL, 10390537468717415060UL));
			_ufle12jhs77_targetConditionId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(5560822096214341257UL, 13891741393878146481UL));
			_ufle12jhs77_userConditionId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(_metaDefault, new BGId(4635459305867907458UL, 4959464754983229357UL));
			_ufle12jhs77_guaranteedHitFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5086269220495800226UL, 6394174357496699269UL));
			_ufle12jhs77_pierceBarrierFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(4616835570647001322UL, 3697461208925056143UL));
			_ufle12jhs77_pierceShieldFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5564772478280759691UL, 16934115719918024364UL));
			_ufle12jhs77_changeWeatherFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5614678605245773606UL, 17296149091790613183UL));
			_ufle12jhs77_changeFieldFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5525816365690520623UL, 8949687732978284214UL));
			_ufle12jhs77_fixedDamageFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(5307445969301647497UL, 14746900741543460512UL));
			_ufle12jhs77_selfDestructFlag = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(4625049298063639268UL, 4654949951376471970UL));
			_edeht3sdad33_skillKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5565842710707110596UL, 11905549077091789974UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_skillId = null;
			_ufle12jhs77_nameTextId = null;
			_ufle12jhs77_descTextId = null;
			_ufle12jhs77_memo = null;
			_ufle12jhs77_effectName = null;
			_ufle12jhs77_hpCostType = null;
			_ufle12jhs77_hpCostRate = null;
			_ufle12jhs77_targetRange = null;
			_ufle12jhs77_skillCategory = null;
			_ufle12jhs77_activationTiming = null;
			_ufle12jhs77_effectTarget = null;
			_ufle12jhs77_effectType = null;
			_ufle12jhs77_physicMagicType = null;
			_ufle12jhs77_power = null;
			_ufle12jhs77_accuracy = null;
			_ufle12jhs77_hpDrainRate = null;
			_ufle12jhs77_powerAtMaxHp = null;
			_ufle12jhs77_powerAtMinHp = null;
			_ufle12jhs77_applyBuffBeforeAttack = null;
			_ufle12jhs77_barrierCount = null;
			_ufle12jhs77_barrierType = null;
			_ufle12jhs77_barrierMaxStacks = null;
			_ufle12jhs77_barrierTurnCount = null;
			_ufle12jhs77_barrierConsumeTiming = null;
			_ufle12jhs77_shieldCount = null;
			_ufle12jhs77_shieldReduceRate = null;
			_ufle12jhs77_shieldReduceValue = null;
			_ufle12jhs77_shieldType = null;
			_ufle12jhs77_shieldTurnCount = null;
			_ufle12jhs77_shieldConsumeTiming = null;
			_ufle12jhs77_minHitCount = null;
			_ufle12jhs77_maxHitCount = null;
			_ufle12jhs77_multiHitProbability = null;
			_ufle12jhs77_criticalRank = null;
			_ufle12jhs77_fixedDamageValue = null;
			_ufle12jhs77_weatherId = null;
			_ufle12jhs77_fieldId = null;
			_ufle12jhs77_specialEffectConditionId = null;
			_ufle12jhs77_actionPriority = null;
			_ufle12jhs77_jankenId = null;
			_ufle12jhs77_targetBuffId = null;
			_ufle12jhs77_userBuffId = null;
			_ufle12jhs77_targetConditionId = null;
			_ufle12jhs77_userConditionId = null;
			_ufle12jhs77_guaranteedHitFlag = null;
			_ufle12jhs77_pierceBarrierFlag = null;
			_ufle12jhs77_pierceShieldFlag = null;
			_ufle12jhs77_changeWeatherFlag = null;
			_ufle12jhs77_changeFieldFlag = null;
			_ufle12jhs77_fixedDamageFlag = null;
			_ufle12jhs77_selfDestructFlag = null;
			_edeht3sdad33_skillKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new skill(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new skill(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "skill";
			public const string name = "name";
			public const string skillId = "skillId";
			public const string nameTextId = "nameTextId";
			public const string descTextId = "descTextId";
			public const string memo = "memo";
			public const string effectName = "effectName";
			public const string hpCostType = "hpCostType";
			public const string hpCostRate = "hpCostRate";
			public const string targetRange = "targetRange";
			public const string skillCategory = "skillCategory";
			public const string activationTiming = "activationTiming";
			public const string effectTarget = "effectTarget";
			public const string effectType = "effectType";
			public const string physicMagicType = "physicMagicType";
			public const string power = "power";
			public const string accuracy = "accuracy";
			public const string hpDrainRate = "hpDrainRate";
			public const string powerAtMaxHp = "powerAtMaxHp";
			public const string powerAtMinHp = "powerAtMinHp";
			public const string applyBuffBeforeAttack = "applyBuffBeforeAttack";
			public const string barrierCount = "barrierCount";
			public const string barrierType = "barrierType";
			public const string barrierMaxStacks = "barrierMaxStacks";
			public const string barrierTurnCount = "barrierTurnCount";
			public const string barrierConsumeTiming = "barrierConsumeTiming";
			public const string shieldCount = "shieldCount";
			public const string shieldReduceRate = "shieldReduceRate";
			public const string shieldReduceValue = "shieldReduceValue";
			public const string shieldType = "shieldType";
			public const string shieldTurnCount = "shieldTurnCount";
			public const string shieldConsumeTiming = "shieldConsumeTiming";
			public const string minHitCount = "minHitCount";
			public const string maxHitCount = "maxHitCount";
			public const string multiHitProbability = "multiHitProbability";
			public const string criticalRank = "criticalRank";
			public const string fixedDamageValue = "fixedDamageValue";
			public const string weatherId = "weatherId";
			public const string fieldId = "fieldId";
			public const string specialEffectConditionId = "specialEffectConditionId";
			public const string actionPriority = "actionPriority";
			public const string jankenId = "jankenId";
			public const string targetBuffId = "targetBuffId";
			public const string userBuffId = "userBuffId";
			public const string targetConditionId = "targetConditionId";
			public const string userConditionId = "userConditionId";
			public const string guaranteedHitFlag = "guaranteedHitFlag";
			public const string pierceBarrierFlag = "pierceBarrierFlag";
			public const string pierceShieldFlag = "pierceShieldFlag";
			public const string changeWeatherFlag = "changeWeatherFlag";
			public const string changeFieldFlag = "changeFieldFlag";
			public const string fixedDamageFlag = "fixedDamageFlag";
			public const string selfDestructFlag = "selfDestructFlag";
			public const string skillKey = "skillKey";
		}
	}
}
#pragma warning restore 414
