using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class specialeffect : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4735545075110796836UL,10101841681625043122UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String spEffectId
		{
			get => _spEffectId[Index];
			set => _spEffectId[Index] = value;
		}
		public System.String memo
		{
			get => _memo[Index];
			set => _memo[Index] = value;
		}
		public System.String conditionType1
		{
			get => _conditionType1[Index];
			set => _conditionType1[Index] = value;
		}
		public System.String conditionValue1
		{
			get => _conditionValue1[Index];
			set => _conditionValue1[Index] = value;
		}
		public System.Int32 damageCorrection1
		{
			get => _damageCorrection1[Index];
			set => _damageCorrection1.SetValue(this, value);
		}
		public System.String conditionType2
		{
			get => _conditionType2[Index];
			set => _conditionType2[Index] = value;
		}
		public System.String conditionValue2
		{
			get => _conditionValue2[Index];
			set => _conditionValue2[Index] = value;
		}
		public System.Int32 damageCorrection2
		{
			get => _damageCorrection2[Index];
			set => _damageCorrection2.SetValue(this, value);
		}
		public System.String conditionType3
		{
			get => _conditionType3[Index];
			set => _conditionType3[Index] = value;
		}
		public System.String conditionValue3
		{
			get => _conditionValue3[Index];
			set => _conditionValue3[Index] = value;
		}
		public System.Int32 damageCorrection3
		{
			get => _damageCorrection3[Index];
			set => _damageCorrection3.SetValue(this, value);
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4615984159259696163UL, 10067863688096160401UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_spEffectId;
		public static BansheeGz.BGDatabase.BGFieldString _spEffectId => _ufle12jhs77_spEffectId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5699840287713939633UL, 5446297069341614520UL), () => _ufle12jhs77_spEffectId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_memo;
		public static BansheeGz.BGDatabase.BGFieldString _memo => _ufle12jhs77_memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5603206257303590660UL, 16318481439910158004UL), () => _ufle12jhs77_memo = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_conditionType1;
		public static BansheeGz.BGDatabase.BGFieldString _conditionType1 => _ufle12jhs77_conditionType1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5084704343356318772UL, 11388628223106567334UL), () => _ufle12jhs77_conditionType1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_conditionValue1;
		public static BansheeGz.BGDatabase.BGFieldString _conditionValue1 => _ufle12jhs77_conditionValue1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5344897863701562020UL, 3385382569248164265UL), () => _ufle12jhs77_conditionValue1 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_damageCorrection1;
		public static BansheeGz.BGDatabase.BGFieldInt _damageCorrection1 => _ufle12jhs77_damageCorrection1 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4855434332405180354UL, 40877055858724241UL), () => _ufle12jhs77_damageCorrection1 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_conditionType2;
		public static BansheeGz.BGDatabase.BGFieldString _conditionType2 => _ufle12jhs77_conditionType2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5410805846312520704UL, 17492667891836815267UL), () => _ufle12jhs77_conditionType2 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_conditionValue2;
		public static BansheeGz.BGDatabase.BGFieldString _conditionValue2 => _ufle12jhs77_conditionValue2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5142584646834998654UL, 6188544061847811731UL), () => _ufle12jhs77_conditionValue2 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_damageCorrection2;
		public static BansheeGz.BGDatabase.BGFieldInt _damageCorrection2 => _ufle12jhs77_damageCorrection2 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4782085022793256782UL, 7581158997562020785UL), () => _ufle12jhs77_damageCorrection2 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_conditionType3;
		public static BansheeGz.BGDatabase.BGFieldString _conditionType3 => _ufle12jhs77_conditionType3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4911696522338212436UL, 1685449695103960243UL), () => _ufle12jhs77_conditionType3 = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_conditionValue3;
		public static BansheeGz.BGDatabase.BGFieldString _conditionValue3 => _ufle12jhs77_conditionValue3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5230181024100881701UL, 1812998626494432909UL), () => _ufle12jhs77_conditionValue3 = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_damageCorrection3;
		public static BansheeGz.BGDatabase.BGFieldInt _damageCorrection3 => _ufle12jhs77_damageCorrection3 ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5686110017848561673UL, 8043279970401796531UL), () => _ufle12jhs77_damageCorrection3 = null);
		public List<Iono.MasterData.inventory> RelatedinventoryListUsingspEffectIdRelation => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.inventory>(Iono.MasterData.inventory._spEffectId, Id);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_spEffectKey;
		public static BansheeGz.BGDatabase.BGKey _spEffectKey => _edeht3sdad33_spEffectKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5383954852498610357UL, 16536034631278992UL), () => _edeht3sdad33_spEffectKey = null);
		private specialeffect() : base(MetaDefault) {}
		private specialeffect(BGId id) : base(MetaDefault, id) {}
		private specialeffect(BGMetaEntity meta) : base(meta) {}
		private specialeffect(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static specialeffect FindEntity(Predicate<specialeffect> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<specialeffect> FindEntities(Predicate<specialeffect> filter, List<specialeffect> result=null, Comparison<specialeffect> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<specialeffect> action, Predicate<specialeffect> filter=null, Comparison<specialeffect> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static specialeffect GetEntity(BGId entityId) => (specialeffect) MetaDefault.GetEntity(entityId);
		public static specialeffect GetEntity(int index) => (specialeffect) MetaDefault[index];
		public static specialeffect GetEntity(string entityName) => (specialeffect) MetaDefault.GetEntity(entityName);
		public static specialeffect NewEntity() => (specialeffect) MetaDefault.NewEntity();
		public static specialeffect NewEntity(BGId entityId) => (specialeffect) MetaDefault.NewEntity(entityId);
		public static specialeffect NewEntity(Action<specialeffect> callback) => (specialeffect) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((specialeffect)entity)));
		public List<Iono.MasterData.inventory> FillRelatedinventoryListUsingspEffectIdRelation(List<Iono.MasterData.inventory> result) => BGCodeGenUtils.GetRelatedInbound<Iono.MasterData.inventory>(Iono.MasterData.inventory._spEffectId, Id, result);
		public static specialeffect GetEntityByKeyspEffectKey(System.String spEffectId) => (specialeffect) _spEffectKey.GetEntityByKey<System.String>(spEffectId);
		public static List<specialeffect> GetEntitiesByKeyspEffectKey(System.String spEffectId, List<specialeffect> result=null) => _spEffectKey.GetEntitiesByKey<specialeffect, System.String>(result, spEffectId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4735545075110796836UL,10101841681625043122UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4615984159259696163UL, 10067863688096160401UL));
			_ufle12jhs77_spEffectId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5699840287713939633UL, 5446297069341614520UL));
			_ufle12jhs77_memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5603206257303590660UL, 16318481439910158004UL));
			_ufle12jhs77_conditionType1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5084704343356318772UL, 11388628223106567334UL));
			_ufle12jhs77_conditionValue1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5344897863701562020UL, 3385382569248164265UL));
			_ufle12jhs77_damageCorrection1 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4855434332405180354UL, 40877055858724241UL));
			_ufle12jhs77_conditionType2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5410805846312520704UL, 17492667891836815267UL));
			_ufle12jhs77_conditionValue2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5142584646834998654UL, 6188544061847811731UL));
			_ufle12jhs77_damageCorrection2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4782085022793256782UL, 7581158997562020785UL));
			_ufle12jhs77_conditionType3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4911696522338212436UL, 1685449695103960243UL));
			_ufle12jhs77_conditionValue3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5230181024100881701UL, 1812998626494432909UL));
			_ufle12jhs77_damageCorrection3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5686110017848561673UL, 8043279970401796531UL));
			_edeht3sdad33_spEffectKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5383954852498610357UL, 16536034631278992UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_spEffectId = null;
			_ufle12jhs77_memo = null;
			_ufle12jhs77_conditionType1 = null;
			_ufle12jhs77_conditionValue1 = null;
			_ufle12jhs77_damageCorrection1 = null;
			_ufle12jhs77_conditionType2 = null;
			_ufle12jhs77_conditionValue2 = null;
			_ufle12jhs77_damageCorrection2 = null;
			_ufle12jhs77_conditionType3 = null;
			_ufle12jhs77_conditionValue3 = null;
			_ufle12jhs77_damageCorrection3 = null;
			_edeht3sdad33_spEffectKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new specialeffect(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new specialeffect(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "specialeffect";
			public const string name = "name";
			public const string spEffectId = "spEffectId";
			public const string memo = "memo";
			public const string conditionType1 = "conditionType1";
			public const string conditionValue1 = "conditionValue1";
			public const string damageCorrection1 = "damageCorrection1";
			public const string conditionType2 = "conditionType2";
			public const string conditionValue2 = "conditionValue2";
			public const string damageCorrection2 = "damageCorrection2";
			public const string conditionType3 = "conditionType3";
			public const string conditionValue3 = "conditionValue3";
			public const string damageCorrection3 = "damageCorrection3";
			public const string spEffectKey = "spEffectKey";
		}
	}
}
#pragma warning restore 414
