using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class TextMaster : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5262983981033625779UL,14589872823870326447UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String textID
		{
			get => _textID[Index];
			set => _textID[Index] = value;
		}
		public System.String ja
		{
			get => _ja[Index];
			set => _ja[Index] = value;
		}
		public System.String Memo
		{
			get => _Memo[Index];
			set => _Memo[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4728355379862078337UL, 13545583819314918563UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_textID;
		public static BansheeGz.BGDatabase.BGFieldString _textID => _ufle12jhs77_textID ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4742589140230484021UL, 12495723989180760509UL), () => _ufle12jhs77_textID = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_ja;
		public static BansheeGz.BGDatabase.BGFieldString _ja => _ufle12jhs77_ja ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5639682639119322305UL, 9792442332739474850UL), () => _ufle12jhs77_ja = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Memo;
		public static BansheeGz.BGDatabase.BGFieldString _Memo => _ufle12jhs77_Memo ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5380943173284004823UL, 543302453305466774UL), () => _ufle12jhs77_Memo = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_key_textId;
		public static BansheeGz.BGDatabase.BGKey _key_textId => _edeht3sdad33_key_textId ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5165219493976954447UL, 11580807397635497124UL), () => _edeht3sdad33_key_textId = null);
		private TextMaster() : base(MetaDefault) {}
		private TextMaster(BGId id) : base(MetaDefault, id) {}
		private TextMaster(BGMetaEntity meta) : base(meta) {}
		private TextMaster(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static TextMaster FindEntity(Predicate<TextMaster> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<TextMaster> FindEntities(Predicate<TextMaster> filter, List<TextMaster> result=null, Comparison<TextMaster> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<TextMaster> action, Predicate<TextMaster> filter=null, Comparison<TextMaster> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static TextMaster GetEntity(BGId entityId) => (TextMaster) MetaDefault.GetEntity(entityId);
		public static TextMaster GetEntity(int index) => (TextMaster) MetaDefault[index];
		public static TextMaster GetEntity(string entityName) => (TextMaster) MetaDefault.GetEntity(entityName);
		public static TextMaster NewEntity() => (TextMaster) MetaDefault.NewEntity();
		public static TextMaster NewEntity(BGId entityId) => (TextMaster) MetaDefault.NewEntity(entityId);
		public static TextMaster NewEntity(Action<TextMaster> callback) => (TextMaster) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((TextMaster)entity)));
		public static TextMaster GetEntityByKeykey_textId(System.String textID) => (TextMaster) _key_textId.GetEntityByKey<System.String>(textID);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5262983981033625779UL,14589872823870326447UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4728355379862078337UL, 13545583819314918563UL));
			_ufle12jhs77_textID = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4742589140230484021UL, 12495723989180760509UL));
			_ufle12jhs77_ja = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5639682639119322305UL, 9792442332739474850UL));
			_ufle12jhs77_Memo = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5380943173284004823UL, 543302453305466774UL));
			_edeht3sdad33_key_textId = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5165219493976954447UL, 11580807397635497124UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_textID = null;
			_ufle12jhs77_ja = null;
			_ufle12jhs77_Memo = null;
			_edeht3sdad33_key_textId = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new TextMaster(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new TextMaster(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "TextMaster";
			public const string name = "name";
			public const string textID = "textID";
			public const string ja = "ja";
			public const string Memo = "Memo";
			public const string key_textId = "key_textId";
		}
	}
}
#pragma warning restore 414
