using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class typeCompatibility : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5224719057282907180UL,6201329996867995580UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String typeId
		{
			get => _typeId[Index];
			set => _typeId[Index] = value;
		}
		public System.Int32 typeNormal
		{
			get => _typeNormal[Index];
			set => _typeNormal.SetValue(this, value);
		}
		public System.Int32 typeFire
		{
			get => _typeFire[Index];
			set => _typeFire.SetValue(this, value);
		}
		public System.Int32 typeWater
		{
			get => _typeWater[Index];
			set => _typeWater.SetValue(this, value);
		}
		public System.Int32 typeElectric
		{
			get => _typeElectric[Index];
			set => _typeElectric.SetValue(this, value);
		}
		public System.Int32 typeGrass
		{
			get => _typeGrass[Index];
			set => _typeGrass.SetValue(this, value);
		}
		public System.Int32 typeIce
		{
			get => _typeIce[Index];
			set => _typeIce.SetValue(this, value);
		}
		public System.Int32 typeFighting
		{
			get => _typeFighting[Index];
			set => _typeFighting.SetValue(this, value);
		}
		public System.Int32 typePoison
		{
			get => _typePoison[Index];
			set => _typePoison.SetValue(this, value);
		}
		public System.Int32 typeGround
		{
			get => _typeGround[Index];
			set => _typeGround.SetValue(this, value);
		}
		public System.Int32 typeFlying
		{
			get => _typeFlying[Index];
			set => _typeFlying.SetValue(this, value);
		}
		public System.Int32 typePsychic
		{
			get => _typePsychic[Index];
			set => _typePsychic.SetValue(this, value);
		}
		public System.Int32 typeBug
		{
			get => _typeBug[Index];
			set => _typeBug.SetValue(this, value);
		}
		public System.Int32 typeRock
		{
			get => _typeRock[Index];
			set => _typeRock.SetValue(this, value);
		}
		public System.Int32 typeGhost
		{
			get => _typeGhost[Index];
			set => _typeGhost.SetValue(this, value);
		}
		public System.Int32 typeDragon
		{
			get => _typeDragon[Index];
			set => _typeDragon.SetValue(this, value);
		}
		public System.Int32 typeDark
		{
			get => _typeDark[Index];
			set => _typeDark.SetValue(this, value);
		}
		public System.Int32 typeSteel
		{
			get => _typeSteel[Index];
			set => _typeSteel.SetValue(this, value);
		}
		public System.Int32 typeFairy
		{
			get => _typeFairy[Index];
			set => _typeFairy.SetValue(this, value);
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4614120048838770181UL, 9182269960505153694UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_typeId;
		public static BansheeGz.BGDatabase.BGFieldString _typeId => _ufle12jhs77_typeId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5487992311467773535UL, 3658109906724506270UL), () => _ufle12jhs77_typeId = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeNormal;
		public static BansheeGz.BGDatabase.BGFieldInt _typeNormal => _ufle12jhs77_typeNormal ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5263641030187492072UL, 1557598411138583432UL), () => _ufle12jhs77_typeNormal = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeFire;
		public static BansheeGz.BGDatabase.BGFieldInt _typeFire => _ufle12jhs77_typeFire ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4626478563673274391UL, 17305593359083548058UL), () => _ufle12jhs77_typeFire = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeWater;
		public static BansheeGz.BGDatabase.BGFieldInt _typeWater => _ufle12jhs77_typeWater ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5422153042225921787UL, 1927153451905170338UL), () => _ufle12jhs77_typeWater = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeElectric;
		public static BansheeGz.BGDatabase.BGFieldInt _typeElectric => _ufle12jhs77_typeElectric ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4953182388322203509UL, 5779914060623339689UL), () => _ufle12jhs77_typeElectric = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeGrass;
		public static BansheeGz.BGDatabase.BGFieldInt _typeGrass => _ufle12jhs77_typeGrass ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5306776043533224922UL, 5992270903673769394UL), () => _ufle12jhs77_typeGrass = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeIce;
		public static BansheeGz.BGDatabase.BGFieldInt _typeIce => _ufle12jhs77_typeIce ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5738472233180683205UL, 12230920567929529519UL), () => _ufle12jhs77_typeIce = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeFighting;
		public static BansheeGz.BGDatabase.BGFieldInt _typeFighting => _ufle12jhs77_typeFighting ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4759298436964166315UL, 3818705429383687862UL), () => _ufle12jhs77_typeFighting = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typePoison;
		public static BansheeGz.BGDatabase.BGFieldInt _typePoison => _ufle12jhs77_typePoison ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5545442699261356991UL, 6876891155226281366UL), () => _ufle12jhs77_typePoison = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeGround;
		public static BansheeGz.BGDatabase.BGFieldInt _typeGround => _ufle12jhs77_typeGround ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5189787413586165869UL, 6846777815896518058UL), () => _ufle12jhs77_typeGround = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeFlying;
		public static BansheeGz.BGDatabase.BGFieldInt _typeFlying => _ufle12jhs77_typeFlying ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4949596983316111133UL, 16687354416484181647UL), () => _ufle12jhs77_typeFlying = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typePsychic;
		public static BansheeGz.BGDatabase.BGFieldInt _typePsychic => _ufle12jhs77_typePsychic ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4746593253453674518UL, 18245615560319760047UL), () => _ufle12jhs77_typePsychic = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeBug;
		public static BansheeGz.BGDatabase.BGFieldInt _typeBug => _ufle12jhs77_typeBug ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5205382101776561411UL, 17982494269893299604UL), () => _ufle12jhs77_typeBug = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeRock;
		public static BansheeGz.BGDatabase.BGFieldInt _typeRock => _ufle12jhs77_typeRock ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5217412554646600456UL, 8358844179238720649UL), () => _ufle12jhs77_typeRock = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeGhost;
		public static BansheeGz.BGDatabase.BGFieldInt _typeGhost => _ufle12jhs77_typeGhost ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5214187285417918631UL, 9509363925377190808UL), () => _ufle12jhs77_typeGhost = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeDragon;
		public static BansheeGz.BGDatabase.BGFieldInt _typeDragon => _ufle12jhs77_typeDragon ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5370164547221752111UL, 10716875351815048322UL), () => _ufle12jhs77_typeDragon = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeDark;
		public static BansheeGz.BGDatabase.BGFieldInt _typeDark => _ufle12jhs77_typeDark ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5151899037259993337UL, 122929668456730277UL), () => _ufle12jhs77_typeDark = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeSteel;
		public static BansheeGz.BGDatabase.BGFieldInt _typeSteel => _ufle12jhs77_typeSteel ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4971369248438536954UL, 7940383754764567173UL), () => _ufle12jhs77_typeSteel = null);
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_typeFairy;
		public static BansheeGz.BGDatabase.BGFieldInt _typeFairy => _ufle12jhs77_typeFairy ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5079779118585905173UL, 7314807089545377433UL), () => _ufle12jhs77_typeFairy = null);
		private typeCompatibility() : base(MetaDefault) {}
		private typeCompatibility(BGId id) : base(MetaDefault, id) {}
		private typeCompatibility(BGMetaEntity meta) : base(meta) {}
		private typeCompatibility(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static typeCompatibility FindEntity(Predicate<typeCompatibility> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<typeCompatibility> FindEntities(Predicate<typeCompatibility> filter, List<typeCompatibility> result=null, Comparison<typeCompatibility> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<typeCompatibility> action, Predicate<typeCompatibility> filter=null, Comparison<typeCompatibility> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static typeCompatibility GetEntity(BGId entityId) => (typeCompatibility) MetaDefault.GetEntity(entityId);
		public static typeCompatibility GetEntity(int index) => (typeCompatibility) MetaDefault[index];
		public static typeCompatibility GetEntity(string entityName) => (typeCompatibility) MetaDefault.GetEntity(entityName);
		public static typeCompatibility NewEntity() => (typeCompatibility) MetaDefault.NewEntity();
		public static typeCompatibility NewEntity(BGId entityId) => (typeCompatibility) MetaDefault.NewEntity(entityId);
		public static typeCompatibility NewEntity(Action<typeCompatibility> callback) => (typeCompatibility) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((typeCompatibility)entity)));
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5224719057282907180UL,6201329996867995580UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4614120048838770181UL, 9182269960505153694UL));
			_ufle12jhs77_typeId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5487992311467773535UL, 3658109906724506270UL));
			_ufle12jhs77_typeNormal = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5263641030187492072UL, 1557598411138583432UL));
			_ufle12jhs77_typeFire = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4626478563673274391UL, 17305593359083548058UL));
			_ufle12jhs77_typeWater = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5422153042225921787UL, 1927153451905170338UL));
			_ufle12jhs77_typeElectric = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4953182388322203509UL, 5779914060623339689UL));
			_ufle12jhs77_typeGrass = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5306776043533224922UL, 5992270903673769394UL));
			_ufle12jhs77_typeIce = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5738472233180683205UL, 12230920567929529519UL));
			_ufle12jhs77_typeFighting = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4759298436964166315UL, 3818705429383687862UL));
			_ufle12jhs77_typePoison = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5545442699261356991UL, 6876891155226281366UL));
			_ufle12jhs77_typeGround = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5189787413586165869UL, 6846777815896518058UL));
			_ufle12jhs77_typeFlying = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4949596983316111133UL, 16687354416484181647UL));
			_ufle12jhs77_typePsychic = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4746593253453674518UL, 18245615560319760047UL));
			_ufle12jhs77_typeBug = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5205382101776561411UL, 17982494269893299604UL));
			_ufle12jhs77_typeRock = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5217412554646600456UL, 8358844179238720649UL));
			_ufle12jhs77_typeGhost = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5214187285417918631UL, 9509363925377190808UL));
			_ufle12jhs77_typeDragon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5370164547221752111UL, 10716875351815048322UL));
			_ufle12jhs77_typeDark = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5151899037259993337UL, 122929668456730277UL));
			_ufle12jhs77_typeSteel = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4971369248438536954UL, 7940383754764567173UL));
			_ufle12jhs77_typeFairy = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5079779118585905173UL, 7314807089545377433UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_typeId = null;
			_ufle12jhs77_typeNormal = null;
			_ufle12jhs77_typeFire = null;
			_ufle12jhs77_typeWater = null;
			_ufle12jhs77_typeElectric = null;
			_ufle12jhs77_typeGrass = null;
			_ufle12jhs77_typeIce = null;
			_ufle12jhs77_typeFighting = null;
			_ufle12jhs77_typePoison = null;
			_ufle12jhs77_typeGround = null;
			_ufle12jhs77_typeFlying = null;
			_ufle12jhs77_typePsychic = null;
			_ufle12jhs77_typeBug = null;
			_ufle12jhs77_typeRock = null;
			_ufle12jhs77_typeGhost = null;
			_ufle12jhs77_typeDragon = null;
			_ufle12jhs77_typeDark = null;
			_ufle12jhs77_typeSteel = null;
			_ufle12jhs77_typeFairy = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new typeCompatibility(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new typeCompatibility(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "typeCompatibility";
			public const string name = "name";
			public const string typeId = "typeId";
			public const string typeNormal = "typeNormal";
			public const string typeFire = "typeFire";
			public const string typeWater = "typeWater";
			public const string typeElectric = "typeElectric";
			public const string typeGrass = "typeGrass";
			public const string typeIce = "typeIce";
			public const string typeFighting = "typeFighting";
			public const string typePoison = "typePoison";
			public const string typeGround = "typeGround";
			public const string typeFlying = "typeFlying";
			public const string typePsychic = "typePsychic";
			public const string typeBug = "typeBug";
			public const string typeRock = "typeRock";
			public const string typeGhost = "typeGhost";
			public const string typeDragon = "typeDragon";
			public const string typeDark = "typeDark";
			public const string typeSteel = "typeSteel";
			public const string typeFairy = "typeFairy";
		}
	}
}
#pragma warning restore 414
