using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace Iono.MasterData
{

	[Preserve]
	public sealed partial class type : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5486720170434457139UL,8933241360762839211UL), () => _metaDefault = null);
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String name
		{
			get => _name[Index];
			set => _name[Index] = value;
		}
		public System.String typeId
		{
			get => _typeId[Index];
			set => _typeId[Index] = value;
		}
		public System.String resourceId
		{
			get => _resourceId[Index];
			set => _resourceId[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4652978140274526187UL, 17089653820275030181UL), () => _ufle12jhs77_name = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_typeId;
		public static BansheeGz.BGDatabase.BGFieldString _typeId => _ufle12jhs77_typeId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5457999410012519271UL, 3561462322462045312UL), () => _ufle12jhs77_typeId = null);
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_resourceId;
		public static BansheeGz.BGDatabase.BGFieldString _resourceId => _ufle12jhs77_resourceId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4653291197613326685UL, 11071715819853603991UL), () => _ufle12jhs77_resourceId = null);
		private static BansheeGz.BGDatabase.BGKey _edeht3sdad33_typeKey;
		public static BansheeGz.BGDatabase.BGKey _typeKey => _edeht3sdad33_typeKey ??= BGCodeGenUtils.GetKey(MetaDefault, new BGId(5315714938949888301UL, 11490291428060841866UL), () => _edeht3sdad33_typeKey = null);
		private type() : base(MetaDefault) {}
		private type(BGId id) : base(MetaDefault, id) {}
		private type(BGMetaEntity meta) : base(meta) {}
		private type(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static type FindEntity(Predicate<type> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<type> FindEntities(Predicate<type> filter, List<type> result=null, Comparison<type> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<type> action, Predicate<type> filter=null, Comparison<type> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static type GetEntity(BGId entityId) => (type) MetaDefault.GetEntity(entityId);
		public static type GetEntity(int index) => (type) MetaDefault[index];
		public static type GetEntity(string entityName) => (type) MetaDefault.GetEntity(entityName);
		public static type NewEntity() => (type) MetaDefault.NewEntity();
		public static type NewEntity(BGId entityId) => (type) MetaDefault.NewEntity(entityId);
		public static type NewEntity(Action<type> callback) => (type) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((type)entity)));
		public static type GetEntityByKeytypeKey(System.String typeId) => (type) _typeKey.GetEntityByKey<System.String>(typeId);
		public static void InitializeCodeGenRuntime()
		{
			_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5486720170434457139UL,8933241360762839211UL), ReleaseCodeGenRuntime);
			_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4652978140274526187UL, 17089653820275030181UL));
			_ufle12jhs77_typeId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5457999410012519271UL, 3561462322462045312UL));
			_ufle12jhs77_resourceId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4653291197613326685UL, 11071715819853603991UL));
			_edeht3sdad33_typeKey = BGCodeGenUtils.GetKey(_metaDefault, new BGId(5315714938949888301UL, 11490291428060841866UL));
		}
		public static void ReleaseCodeGenRuntime()
		{
			_metaDefault = null;
			_ufle12jhs77_name = null;
			_ufle12jhs77_typeId = null;
			_ufle12jhs77_resourceId = null;
			_edeht3sdad33_typeKey = null;
		}

		[Preserve]
		public sealed class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new type(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new type(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "type";
			public const string name = "name";
			public const string typeId = "typeId";
			public const string resourceId = "resourceId";
			public const string typeKey = "typeKey";
		}
	}
}
#pragma warning restore 414
